docs: add windows support communication to README
jina-ai/jina pull request #1130
Opened 2020-10-22 09:00 UTC by pswu11

Added some communication in README for windows support as suggested in [https://github.com/jina-ai/examples/issues/246](url)

2020-10-22 10:37 UTC, hanxiao requested changes
This is written in docs already, https://docs.jina.ai/chapters/install/via-pip.html?highlight=windows#on-windows-and-other-oses

2020-10-22 13:56 UTC, bwanglzu submitted a review, later dismissed
do you think it's better to rephrase Windows environment to Microsoft Windows?

2020-10-22 14:02 UTC, alexcg1 commented
> This is written in docs already, https://docs.jina.ai/chapters/install/via-pip.html?highlight=windows#on-windows-and-other-oses (@hanxiao)

Yup, it's already in the docs. I think it'd be good to reference that page at top of each example so users don't waste their time and get a bad impression of us

2020-10-22 14:13 UTC, alexcg1 commented
I think:

- Let's add it in the core repo, but not so obviously. Perhaps under 'Get Started'
- Add to top of each example in a more obvious way

In both cases, link to the page @hanxiao mentioned

2020-10-22 17:16 UTC, bhavsarpratik commented on README.md
> +### Windows Support
Can use this emoji 
https://emojipedia.org/warning/

2020-10-23 08:04 UTC, pswu11 commented
@hanxiao @alexcg1 
I revised the communication accordingly. Instead of having an independent section, just a short sentence that links directly to the section.

2020-10-23 08:30 UTC, alexcg1 commented
Let's change the text:

Old:

```
If you are Windows user, see [this section](https://docs.jina.ai/chapters/install/via-pip.html?highlight=windows#on-windows-and-other-oses)
```

New: 

```
⚠️ We don't currently support Windows, but we're working on it! [See here for more information](https://docs.jina.ai/chapters/install/via-pip.html?highlight=windows#on-windows-and-other-oses).
```

That lets them know immediately we don't support Windows, instead of them having to click the link to find out

2020-10-23 09:28 UTC, pswu11 commented
> Let's change the text:
> 
> Old:
> 
> ```
> If you are Windows user, see [this section](https://docs.jina.ai/chapters/install/via-pip.html?highlight=windows#on-windows-and-other-oses)
> ```
> 
> New:
> 
> ```
> ⚠️ We don't currently support Windows, but we're working on it! [See here for more information](https://docs.jina.ai/chapters/install/via-pip.html?highlight=windows#on-windows-and-other-oses).
> ```
> 
> That lets them know immediately we don't support Windows, instead of them having to click the link to find out

@alexcg1 adjusted based on our discussion

2020-10-23 09:34 UTC, alexcg1 commented
@bwanglzu I don't think we need to specify **Microsoft** Windows. It's not there's any other Windows out there (except X Windows, but that's a whole other thing)

2020-10-23 09:36 UTC, alexcg1 commented
@pswu11 Re your commit message, you'll need to rewrite to make it lower-case otherwise it may fail linting. [Instructions here](https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/changing-a-commit-message). Let me know if you need help!

2020-10-23 11:46 UTC, alexcg1 commented
LGTM. @hanxiao if all good with you we can merge (normally I wouldn't ask about something so small, but this is on our main README after all)

2020-10-23 11:52 UTC, hanxiao approved these changes

2020-10-23 13:39 UTC, merged