chore: add packaging in extra requirements
jina-ai/jina pull request #1150
Opened 2020-10-23 17:41 UTC by JoanFM

**Changes introduced**
Adding `packaging` as requirement for the `hub` so that https://github.com/jina-ai/jina-hub/pull/460 can pass.
It would affect any other `hub` build

2020-10-25 11:58 UTC, hanxiao commented
i think `package` is part of `setuptools`, which user should have after install `pip`?

2020-10-25 16:05 UTC, nan-wang approved these changes
LGTM👍

2020-10-26 07:29 UTC, hanxiao requested changes
for the reason i said

2020-10-26 10:17 UTC, maximilianwerk commented
> i think `packaging` is part of `setuptools`, which user should have after install `pip`?
> 
> i will take a close look tomorrow

I think that is not true. On a fresh `venv`:
```
> python
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> import packaging
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'packaging'
>>> 
```

2020-10-26 10:35 UTC, hanxiao commented
hmm, then this makes `_is_latest_version` unusable, we also use `packaging` in it. need a workaround in another PR

2020-10-26 10:35 UTC, hanxiao approved these changes

2020-10-26 10:35 UTC, merged