fix: pod argument overriden by flow
jina-ai/jina pull request #1189
Opened 2020-10-30 12:21 UTC by maximilianwerk

The explicitly defined values on pod level should have higher priority, then the ones on flow level.

2020-10-30 12:23 UTC, JoanFM requested changes

2020-10-30 12:23 UTC, JoanFM commented on jina/flow/__init__.py
> +        for key, value in op_flow._common_kwargs.items():
missing some tests to show the problem and the feature

2020-10-30 12:34 UTC, JoanFM approved these changes

2020-10-31 21:18 UTC, hanxiao approved these changes

2020-10-31 21:19 UTC, merged