fix(contributing): switch testing to pytest
jina-ai/jina pull request #1207
Opened 2020-11-02 15:06 UTC by alexcg1

Based on discussion in Slack group, adjusted testing section

2020-11-02 15:07 UTC, JoanFM requested changes

2020-11-02 15:07 UTC, JoanFM commented on CONTRIBUTING.md
>  pip install ".[match-py-ver]"
We need to change to `pip install .[test]`

2020-11-02 15:13 UTC, bwanglzu commented
runned `pip install [.test]` and then `pytest -s -v ...`, got:
![image](https://user-images.githubusercontent.com/9794489/97884383-4cd62f00-1d26-11eb-8c33-f8a3395ac8c3.png)

2020-11-02 15:15 UTC, JoanFM commented
> runned `pip install [.test]` and then `pytest -s -v ...`, got:
> ![image](https://user-images.githubusercontent.com/9794489/97884383-4cd62f00-1d26-11eb-8c33-f8a3395ac8c3.png)

Then, we need to rewrite these tests so that they do not depend on these `Min and Max Rankers`, we need to change them by some `MockRankers` done for the tests.

2020-11-02 15:15 UTC, JoanFM commented
> > runned `pip install [.test]` and then `pytest -s -v ...`, got:
> > ![image](https://user-images.githubusercontent.com/9794489/97884383-4cd62f00-1d26-11eb-8c33-f8a3395ac8c3.png)
> 
> Then, we need to rewrite these tests so that they do not depend on these `Min and Max Rankers`, we need to change them by some `MockRankers` done for the tests.

I will do that

2020-11-02 15:19 UTC, JoanFM commented
Created PR #1208

2020-11-02 15:20 UTC, alexcg1 commented
This sounds like a bigger job than first envisaged. Ping me when we're good to move forward! :)

2020-11-02 15:21 UTC, JoanFM commented
the `pip install .[test]` shpuld be put instead of the `[py_match_ver]`, that for sure

2020-11-02 15:42 UTC, JoanFM commented
You should be able to proceed @alexcg1 with the changes requested

2020-11-03 08:54 UTC, hanxiao commented on CONTRIBUTING.md
>  pip install ".[match-py-ver]"
```suggestion
pip install ".[test]"
```

2020-11-03 08:55 UTC, merged