test: refactor test index test
jina-ai/jina pull request #1258
Opened 2020-11-10 16:46 UTC by JoanFM

2020-11-10 21:00 UTC, bwanglzu requested changes

2020-11-10 21:02 UTC, JoanFM commented on tests/unit/test_index.py
> +@pytest.mark.parametrize('random_workspace_name', ['JINA_TEST_INDEX'])
That the yaml file used declares a workspace depending on an env variable

2020-11-10 21:05 UTC, JoanFM commented on tests/unit/test_index.py
> +@pytest.mark.parametrize('random_workspace_name', ['JINA_TEST_INDEX'])
But yes maybe is a mistake from my side

2020-11-10 21:20 UTC, bwanglzu commented on tests/unit/test_index.py
> +@pytest.mark.parametrize('random_workspace_name', ['JINA_TEST_INDEX'])
maybe we can create a new fixture which can takes a specific workspace name as a parameter?

2020-11-11 03:47 UTC, nan-wang requested changes
minor changes

2020-11-11 03:47 UTC, nan-wang commented on tests/unit/test_index.py
> +        print(f' path {path}')
```suggestion
```

2020-11-11 03:47 UTC, nan-wang commented on tests/unit/test_index.py
> +@pytest.mark.parametrize('random_workspace_name', ['JINA_TEST_INDEX'])
That would be helpful.

2020-11-11 08:19 UTC, hanxiao approved these changes

2020-11-11 08:20 UTC, merged