Update README.kr.md
jina-ai/jina pull request #1269
Opened 2020-11-12 06:28 UTC by rabbits99

I uploaded again
sorry for make you confused

2020-11-12 08:01 UTC, JoanFM requested changes

2020-11-12 08:01 UTC, JoanFM commented on .github/i18n/README.kr.md
> -Jina는 Apache License 버전 2.0에 따라 라이센스를 받는다.[전체 라이센스 텍스트는 LICE를 참조하십시오.](LICENSE)
I would suggest to keep this part in original English, at least the `Apache License` part.

2020-11-12 09:33 UTC, JoanFM commented
Bad commit message, please refer to:
- [Commit Message Guideline for the First Time Contributor](https://github.com/jina-ai/jina/issues/553)
- [Contributing Guideline](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md)
#553 :bookmark: Commit Message Guideline for the First Time Contributor
jina-ai/jina | Jun 21st | Added by GitHub
CONTRIBUTING.md
jina-ai/jina | Added by GitHub

2020-11-12 09:33 UTC, JoanFM commented
recheckcla

2020-11-24 22:02 UTC, bwanglzu commented
hi @rabbits99 would you like to continue with this PR? it has been 2 weeks. Please check commit guidelines #553 to update your commit message, and sign the CLA.

2020-11-25 16:26 UTC, rabbits99 commented
yes sorry for keeping wait.

this is sign for cla
I have read the CLA Document and I hereby sign the CLA

2020-11-25 16:34 UTC, bwanglzu commented
@rabbits99 no worries, you need to amend this commit message, otherwise ci will keep failing: 
![image](https://user-images.githubusercontent.com/9794489/100255958-714bb280-2f44-11eb-8948-73a76328c1c6.png)

2020-11-25 17:28 UTC, rabbits99 commented
we have trouble with amending 
so can we create PR again?

2020-11-26 00:14 UTC, nan-wang commented
> we have trouble with amending
> so can we create PR again?

Yes, it is easier to create a PR again.

2020-11-26 11:09 UTC, closed without merging