feat: in collect2matches rank driver keep chunks of matches
jina-ai/jina pull request #1494
Opened 2020-12-19 12:54 UTC by JoanFM

**Changes introduced**
Enable the ability to keep the chunks of the matches with the original retrieval score or distance.

Relates to #1491

2020-12-21 15:29 UTC, nan-wang requested changes

2020-12-21 15:29 UTC, nan-wang commented on jina/drivers/rank/aggregate/__init__.py
> +                 keep_old_matches_as_chunks: bool = False,
```suggestion
                 keep_source_matches_as_chunks: bool = False,
```

2020-12-21 15:29 UTC, nan-wang commented on jina/drivers/rank/aggregate/__init__.py
> +            |-matches: {granularity: k-1} (Ranked according to Ranker Executor)
```suggestion
        document: {granularity: k-1}
                |- chunks: {granularity: k}
                |    |- matches: {granularity: k}
                |
                |- chunks: {granularity: k}
                    |- matches: {granularity: k}
        Output:
        document: {granularity: k-1}
                |- chunks: {granularity: k}
                |    |- matches: {granularity: k}
                |
                |- chunks: {granularity: k}
                |    |- matches: {granularity: k}
                |
                |-matches: {granularity: k-1} (Ranked according to Ranker Executor)
```

2020-12-21 15:29 UTC, nan-wang commented on jina/drivers/rank/aggregate/__init__.py
> +            |- matches: {granularity: k-1} (Sorted according to Ranker Executor)
```suggestion
        Input:
        document: {granularity: k}
            |- matches: {granularity: k}
            
        Output:
        document: {granularity: k}
            |- matches: {granularity: k-1} (Sorted according to Ranker Executor)
```

2020-12-21 15:29 UTC, nan-wang commented on jina/drivers/rank/aggregate/__init__.py
> +class CollectMatches2DocRankDriver(BaseAggregateMatchesRanker):
Not sure about whether it is a better naming. 
```suggestion
class AggregateMatches2DocRankDriver(BaseAggregateMatchesRanker):
```

2020-12-21 16:56 UTC, JoanFM commented
Attention, changes to be added in #1337

2020-12-22 15:26 UTC, hanxiao commented
looks like a conflict in files

2020-12-22 15:51 UTC, JoanFM commented
> looks like a conflict in files

Done!

2020-12-22 18:01 UTC, hanxiao approved these changes

2020-12-22 18:01 UTC, merged