refactor: change metric evaluator name adapt to eval_at
jina-ai/jina pull request #1570
Opened 2020-12-30 19:08 UTC by JoanFM

2020-12-31 10:32 UTC, florian-hoenicke requested changes
line 87 in test_ranking_evaluate_driver  has to be changed to   
`assert doc.evaluations[0].op_name == 'Precision@2'`

Also for some reason the function `test_ranking_evaluate_driver` is there twice. We can remove one of them.

2020-12-31 10:35 UTC, JoanFM commented
> line 87 in test_ranking_evaluate_driver has to be changed to
> `assert doc.evaluations[0].op_name == 'Precision@2'`
> 
> Also for some reason the function `test_ranking_evaluate_driver` is there twice. We can remove one of them.

Is it exactly the same? if it is exactly the same yes we can remove it, otherwise we rename one.

I saw, I want to change to 

`assert doc.evaluations[0].op_name == executor.metric`

Would u have time to do these couple of changes on this branch?

2020-12-31 10:36 UTC, florian-hoenicke commented
sure - I do it

2020-12-31 10:52 UTC, JoanFM commented on tests/unit/drivers/test_rankingevaluation_driver.py
> +        assert doc.evaluations[0].op_name == 'Precision@2'
can u change this to have 
``` executor = PrecisionEvaluator(eval_at=2) 
driver.attach(executor=executor, pea=None)

assert driver.op_name == executor.metric
```
Naming might be wrong, but like this the responsibility of testing the actual name is tested in the executor while the driver tests that the name is taken from executor

2020-12-31 11:40 UTC, JoanFM reviewed
I like it

2020-12-31 11:44 UTC, JoanFM commented
@florian-hoenicke if u can, can u try running jina hello-world and see if the evaluation results are properly shown in the html resulting?

2020-12-31 14:20 UTC, florian-hoenicke commented
As a result I get:
`Precision@50: 65.47% Recall@50: 0.55%`
The precision looks really low to me.
From what I see in the results, it should be much higher.

2020-12-31 14:21 UTC, JoanFM commented
> As a result I get:
> `Precision@50: 65.47% Recall@50: 0.55%`
> The precision looks really low to me.
> From what I see in the results, it should be much higher.

thats okey I just want to check the name

2020-12-31 14:28 UTC, hanxiao requested changes
I removed this intentionally. To me it is redundant as we already have `self.name` for all executor. Can we just use `self.name` instead of creating a new property.

I suggest remove redundant `metric` property and use:
```python
op.name = f'{self.exec.name}@{self.eval_at}'
```

2020-12-31 14:37 UTC, JoanFM commented
> I removed this intentionally. To me it is redundant as we already have `self.name` for all executor. Can we just use `self.name` instead of creating a new property.
> 
> I suggest remove redundant `metric` property and use:
> 
> ```python
> op.name = f'{self.exec.name}@{self.eval_at}'
> ```

it was to mantain alignment with hub but yes we can do this. Just wanted to align all

2020-12-31 14:49 UTC, JoanFM commented
Will do as @hanxiao suggests

2020-12-31 15:09 UTC, florian-hoenicke commented
I created a new pr for the two tests having the same method name.
https://github.com/jina-ai/jina/pull/1573/files

2021-01-04 04:05 UTC, nan-wang submitted a review, later dismissed
LGTM👍

2021-01-05 07:21 UTC, nan-wang commented
The unit test failed
https://github.com/jina-ai/jina/pull/1570/checks?check_run_id=1645486983#step:6:2024

2021-01-05 07:31 UTC, JoanFM commented
> The unit test failed
> https://github.com/jina-ai/jina/pull/1570/checks?check_run_id=1645486983#step:6:2024

Thanks for pointing it out

2021-01-06 03:10 UTC, nan-wang approved these changes
LGTM👍

2021-01-06 03:11 UTC, merged