Feat: cache driver - update delete methods
jina-ai/jina pull request #1630
Opened 2021-01-08 17:14 UTC by cristianmtr

Required for CRUD integration tests
@florian-hoenicke @theUnkownName

2021-01-08 17:31 UTC, JoanFM commented
Keep it as draft if it is not expected to be merged

2021-01-08 17:34 UTC, cristianmtr commented
It is expected to be merged

2021-01-08 17:35 UTC, JoanFM commented
So unit tests must be added

2021-01-08 17:35 UTC, JoanFM requested changes
Unit tests must be added

2021-01-09 08:56 UTC, nan-wang commented
Add some unit tests.

2021-01-11 07:58 UTC, cristianmtr commented
> Add some unit tests.

Thanks for adding them, @nan-wang 

Was not sure this should be merged actually. It was more for sharing a fix that might be required by other crud integration tests. I will get back to it after the stand up today where I'll ask if it's needed

2021-01-13 11:36 UTC, cristianmtr commented
Closing this as not needed. These changes will be added in #1613 . @nan-wang I will add your unit tests there

2021-01-13 11:36 UTC, closed without merging