fix: kv default traversal
jina-ai/jina pull request #1685
Opened 2021-01-14 11:15 UTC by cristianmtr

2021-01-14 11:37 UTC, JoanFM reviewed
@maximilianwerk I think this is the value we should put as default, do you agree?

2021-01-14 12:25 UTC, maximilianwerk commented
> @maximilianwerk I think this is the value we should put as default, do you agree?

Yes.

2021-01-14 12:25 UTC, maximilianwerk submitted a review, later dismissed
LGTM

2021-01-14 17:45 UTC, cristianmtr commented
Some test was failing

2021-01-16 20:58 UTC, florian-hoenicke submitted a review, later dismissed
Nice feature. For most of the real world cases it will make the yaml configuration smaller.
The test fails because there is a `traversal_paths: ['r']` missing on the `SearchRequest` in `tests/integration/crud/yaml/index_kv.yml`.
The test `tests/integration/crud/test_crud.pytest_delete_kv:test_crud.py` fails because it is just using the `kv indexer` and tries to get matches.

2021-01-18 08:21 UTC, cristianmtr commented
> Nice feature. For most of the real world cases it will make the yaml configuration smaller.
> The test fails because there is a `traversal_paths: ['r']` missing on the `SearchRequest` in `tests/integration/crud/yaml/index_kv.yml`.
> The test `tests/integration/crud/test_crud.pytest_delete_kv:test_crud.py` fails because it is just using the `kv indexer` and tries to get matches.

Strange, I cannot reproduce the second one. It passes for me. I fixed the first one and started a new run of the CI. Let's see...

2021-01-18 11:23 UTC, cristianmtr commented
The test `tests/integration/test_helloworld.py::test_helloworld_py` keeps failing in CI, but cannot reproduce locally

2021-01-18 13:03 UTC, JoanFM requested changes

2021-01-18 13:03 UTC, JoanFM commented on tests/unit/drivers/test_kv_search_driver.py
> +        if kwargs.get('traversal_paths') is None:
add `traversal_paths` to set of arguments

2021-01-18 13:23 UTC, cristianmtr commented on tests/unit/drivers/test_kv_search_driver.py
> +    def __init__(self, traversal_paths=['r'], *args, **kwargs):
@JoanFM like so?

2021-01-18 13:23 UTC, JoanFM submitted a review, later dismissed

2021-01-18 13:23 UTC, JoanFM commented on tests/unit/drivers/test_kv_search_driver.py
> +    def __init__(self, traversal_paths=['r'], *args, **kwargs):
yes

2021-01-18 13:56 UTC, theUnkownName approved these changes

2021-01-18 14:21 UTC, JoanFM requested changes

2021-01-18 14:21 UTC, JoanFM commented on tests/integration/test_helloworld.py
> +        f.index(_input_ndarray(targets['index']['data']), batch_size=args.index_request_size)
can u call it `request_size=`?

2021-01-18 14:22 UTC, cristianmtr commented on tests/integration/test_helloworld.py
> +        f.index(_input_ndarray(targets['index']['data']), batch_size=args.index_request_size)
done

2021-01-18 15:28 UTC, JoanFM approved these changes

2021-01-18 15:36 UTC, merged