test: empty or corrupt docs
jina-ai/jina pull request #1700
Opened 2021-01-15 12:47 UTC by cristianmtr

- [x] Only tags
- [ ] Only embedding
- [x] No content
- [ ] Malformed content
- [ ] Different modalities
- [ ] Different shapes, dimensionality

2021-01-15 13:59 UTC, JoanFM requested changes

2021-01-15 13:59 UTC, JoanFM commented on jina/executors/indexers/vector.py
> +            if kwargs.get('keys_precomputed') is not True:
please, use private `_delete` method and do not read from `kwargs` as it is done here, I thought this was removed from the code

2021-01-15 17:25 UTC, cristianmtr commented on jina/executors/indexers/vector.py
> +        self._delete(keys, keys_precomputed=False)
@JoanFM Is this what you mean?

2021-01-15 17:29 UTC, JoanFM commented on jina/executors/indexers/vector.py
> +        self._delete(keys, keys_precomputed=False)
yes

2021-01-19 08:12 UTC, cristianmtr commented on tests/integration/crud_corrupted/test_crud_corrupted.py
> +        d.mime_type = mime_type
You mean the `content`, or the `embedding`?

2021-01-19 08:13 UTC, JoanFM commented on tests/integration/crud_corrupted/test_crud_corrupted.py
> +        d.mime_type = mime_type
the content yes

2021-01-19 11:10 UTC, hanxiao approved these changes

2021-01-19 11:12 UTC, merged