refactor: optional disable uses_b/a if parallel is 1
jina-ai/jina pull request #1711
Opened 2021-01-16 11:44 UTC by JoanFM

**Changes introduced**
Right now if we use `uses_before` or `uses_after` it is added even when parallel is 1. Although it can be desired to have a `uses_after` or `uses_before` it is more common to only want it when there are multiple Peas inside a Pod.

Add an option to disable them if parallel is 1. Like this one can keep the same `Flow` structure for `sharding` and no `sharding` and just parametrize the number of parallels or other options while not wasting CPU and network hops by these extra Peas

2021-01-17 22:11 UTC, florian-hoenicke requested changes
Can we add a small test here?

2021-01-17 22:30 UTC, JoanFM commented
> Can we add a small test here?

sure, wilk

2021-01-18 08:38 UTC, JoanFM commented
> Can we add a small test here?

Done!

2021-01-18 16:23 UTC, nan-wang approved these changes
LGTM👍

2021-01-18 19:23 UTC, merged