refactor: avoid import drivers from types
jina-ai/jina pull request #1759
Opened 2021-01-22 12:54 UTC by JoanFM

2021-01-22 23:11 UTC, JoanFM commented
I think we can invert the logic and have a QueryLang created from a Driver instead of passing a Driver to QueryLang.

2021-01-23 15:56 UTC, nan-wang requested changes
I agree upon that the types should not import drivers because conceptually drivers are one level higher than the types. However, I'm not sure using tuples for initializing `QueryLang` is a good solution. For me, it doesn't feel pythonic.

2021-01-23 15:56 UTC, nan-wang commented on jina/types/querylang/__init__.py
>              s = SliceQL(start=3, end=4)
```suggestion
```

2021-01-23 15:56 UTC, nan-wang commented on jina/types/querylang/__init__.py
>              s.as_pb_object
```suggestion
            ql.as_pb_object
```

2021-01-23 16:01 UTC, JoanFM commented
> I agree upon that the types should not import drivers because conceptually drivers are one level higher than the types. However, I'm not sure using tuples for initializing `QueryLang` is a good solution. For me, it doesn't feel pythonic.

I agree it does not feel the best way, I think what we could do is to have a `namedtuple` and have this creation come from the `Driver`?

Maybe the best solution would be to put `QueryLang` in a different module (in between `types` and `drivers` so that both `Drivers` and `Types` can depend on it. (I think there we could also fit all the `dunderkeys` syntax and so?

2021-01-25 08:24 UTC, JoanFM commented
> I agree upon that the types should not import drivers because conceptually drivers are one level higher than the types. However, I'm not sure using tuples for initializing `QueryLang` is a good solution. For me, it doesn't feel pythonic.

Hey @nan-wang can you see if you like the new changes?

2021-01-26 09:22 UTC, hanxiao approved these changes

2021-01-26 09:22 UTC, merged