fix: show exc info by default
jina-ai/jina pull request #1818
Opened 2021-01-29 17:56 UTC by JoanFM

**Changes introduced**
Productivity boost to capture faster exceptions and problems when defining problems. Also easier for the community to see the problems and to have better reporting

2021-01-29 18:13 UTC, theUnkownName submitted a review, later dismissed

2021-01-29 20:28 UTC, hanxiao commented on jina/peapods/peas/__init__.py
> +                self.logger.error(f'{ex!r} during {self.runtime_cls.__init__!r}' +
```suggestion
                self.logger.error(f'{ex!r} during {self.runtime_cls.__init__!r}' +
```
copy paste glitch

2021-01-29 20:28 UTC, hanxiao commented on jina/peapods/peas/__init__.py
> +            self.logger.error(f'{ex!r} during {self.runtime_cls.__init__!r}' +
```suggestion
            self.logger.error(f'{ex!r} during {self.runtime_cls.__init__!r}' +
```
copy paste glitch

2021-01-29 20:29 UTC, hanxiao commented on jina/peapods/peas/__init__.py
> +                self.logger.error(f'{ex!r} during {self.runtime_cls.__init__!r}' +
```suggestion
                self.logger.error(f'{ex!r} during {self.runtime_cls.__init__!r}' +
```
copy paste glitch

2021-01-29 20:29 UTC, hanxiao commented on jina/peapods/peas/__init__.py
> +                self.logger.error(f'{ex!r} during {self.runtime_cls.__init__!r}' +
```suggestion
                self.logger.error(f'{ex!r} during {self.runtime_cls.__init__!r}' +
```
cpg

2021-01-29 20:30 UTC, hanxiao commented on jina/parsers/peapods/base.py
> +    gp.add_argument('--hide-exc-info', action='store_true', default=True,
```suggestion
    gp.add_argument('--hide-exc-info', action='store_true', default=True,
```
default=True???

2021-01-29 20:31 UTC, hanxiao requested changes
see comments

2021-01-29 21:13 UTC, JoanFM commented on jina/parsers/peapods/base.py
> +    gp.add_argument('--hide-exc-info', action='store_true', default=True,
oh my bad

2021-01-30 09:05 UTC, JoanFM commented on jina/parsers/peapods/base.py
> +    gp.add_argument('--hide-exc-info', action='store_true', default=True,
```suggestion
    gp.add_argument('--hide-exc-info', action='store_true', default=False,
```

2021-01-30 09:06 UTC, JoanFM commented on jina/peapods/peas/__init__.py
> +            self.logger.error(f'{ex!r} during {self.runtime_cls.__init__!r}' +
```suggestion
            self.logger.error(f'{ex!r} during {self.runtime.setup!r}' +
```

2021-01-30 09:07 UTC, JoanFM commented on jina/peapods/peas/__init__.py
> +                self.logger.error(f'{ex!r} during {self.runtime_cls.__init__!r}' +
```suggestion
                self.logger.error(f'{ex!r} during {self.runtime.teardown!r}' +
```

2021-01-30 09:07 UTC, JoanFM commented on jina/peapods/peas/__init__.py
> +                self.logger.error(f'{ex!r} during {self.runtime_cls.__init__!r}' +
```suggestion
                self.logger.error(f'{ex!r} during {self.runtime.cancel!r}' +
```

2021-01-30 09:08 UTC, JoanFM commented on jina/peapods/peas/__init__.py
> +                self.logger.error(f'{ex!r} during {self.runtime_cls.__init__!r}' +
```suggestion
                self.logger.error(f'{ex!r} during {self.runtime.run_forever!r}' +
```

2021-01-30 09:09 UTC, JoanFM commented on jina/peapods/peas/__init__.py
> +                                         f'remote "--hide-exc-info" to see the exception stack in details')
```suggestion
                                         f'remove "--hide-exc-info" to see the exception stack in details')
```

2021-01-30 09:10 UTC, JoanFM commented on jina/peapods/peas/__init__.py
> +                                         f'remote "--hide-exc-info" to see the exception stack in details')
```suggestion
                                         f'remove "--hide-exc-info" to see the exception stack in details')
```

2021-01-30 15:15 UTC, hanxiao approved these changes

2021-01-30 15:27 UTC, merged