feat(driver): add param to use content to predict tags
jina-ai/jina pull request #1957
Opened 2021-02-16 17:53 UTC by deepampatel

https://github.com/jina-ai/jina-hub/issues/3068#issuecomment-778720794

Current implementation of `BasePredictDriver` does not allow to use content of `Document` to predict tags. Methods like Zero shot classification might require a feature extraction pipeline totally independent from the embeddings from encoder and hence can have their own model for predicting tags based on the content.

2021-02-16 18:05 UTC, JoanFM commented
@nan-wang @maximilianwerk @florian-hoenicke @bwanglzu  what is ur opinion here?

Should this info be in the Driver or it should be in the executor and used by the Driver as in the Crafter or in the Ranker.

I think we should see if we need a better organic way to provide parameters from the Executors to be used buly the Driver, since the Executor user may not be familiar with the Driver and we do not want him/her to worry about it.

This pattern is currently present in different shapes in:
- Crafter
- Ranker
- MultiModalEncoder

2021-02-16 18:05 UTC, deepampatel commented on jina/drivers/predict.py
> +            embed_vecs, docs_pts = docs.all_contents
in other places `contents` is used as a generic naming for catching values from document. Use `contents` ?

2021-02-16 18:08 UTC, JoanFM commented on jina/drivers/predict.py
> +            embed_vecs, docs_pts = docs.all_contents
u can use predict_input maybe? Now my doubt is it the parameter should be in the Driver or should be in the Encoder so that the Driver can use it

2021-02-16 18:14 UTC, deepampatel commented on jina/drivers/predict.py
> +            embed_vecs, docs_pts = docs.all_contents
i feel it should be in the executor

2021-02-17 09:03 UTC, maximilianwerk commented
> @nan-wang @maximilianwerk @florian-hoenicke @bwanglzu what is ur opinion here?
> 
> Should this info be in the Driver or it should be in the executor and used by the Driver as in the Crafter or in the Ranker.
> 
> I think we should see if we need a better organic way to provide parameters from the Executors to be used buly the Driver, since the Executor user may not be familiar with the Driver and we do not want him/her to worry about it.
> 
> This pattern is currently present in different shapes in:
> 
>     * Crafter
> 
>     * Ranker
> 
>     * MultiModalEncoder

So Drivers currently are responsible for unpacking data from the docs and packing data back to the docs. We abstracted the traversal away. I wonder, if we should do the same with the data access. (Writing back might come later) Regardless, that would obviously not be part of this PR, but rather a bigger refactoring effort. I would merge this PR as it is and take it as another requirement for the bigger refactoring.

Data access patterns would be:
- apply on flattened/unflattened data structure
- access fields and provide them to the executors in batches (or single and provide and unbatch decorator)

As a consequence, the executor interfaces might unify again a little bit.

2021-02-17 09:10 UTC, JoanFM commented
> > @nan-wang @maximilianwerk @florian-hoenicke @bwanglzu what is ur opinion here?
> > Should this info be in the Driver or it should be in the executor and used by the Driver as in the Crafter or in the Ranker.
> > I think we should see if we need a better organic way to provide parameters from the Executors to be used buly the Driver, since the Executor user may not be familiar with the Driver and we do not want him/her to worry about it.
> > This pattern is currently present in different shapes in:
> > ```
> > * Crafter
> > 
> > * Ranker
> > 
> > * MultiModalEncoder
> > ```
> 
> So Drivers currently are responsible for unpacking data from the docs and packing data back to the docs. We abstracted the traversal away. I wonder, if we should do the same with the data access. (Writing back might come later) Regardless, that would obviously not be part of this PR, but rather a bigger refactoring effort. I would merge this PR after fixing tests and take it as another requirement for the bigger refactoring.
> 
> Data access patterns would be:
> 
> * apply on flattened/unflattened data structure
> * access fields and provide them to the executors in batches (or single and provide and unbatch decorator)
> 
> As a consequence, the executor interfaces might unify again a little bit.

So we agree that the `info` on what to unpack and not should live in the `Executor` to be used by the `Driver` then? Then I would already do this in the `ClassifierExecutor` and then we may think if there is some more clean pattern for the rest of the Drivers, but at least the `Executor` would already have the change applied

2021-02-17 09:27 UTC, maximilianwerk commented
No, I am not convinced. Isn't it the same as the traversal path? The executor gets some data but which exactly is part of the driver!?

2021-02-17 10:02 UTC, JoanFM commented
> No, I am not convinced. Isn't it the same as the traversal path? The executor gets some data but which exactly is part of the driver!?

What I mean is have as params of Executors the fields that it needs to work with. So that the user does not need to touch the Driver if it is only for setting these parameters

2021-02-18 06:38 UTC, nan-wang requested changes

2021-02-18 06:38 UTC, nan-wang commented on jina/drivers/predict.py
> +    def __init__(self, executor: str = None, method: str = 'predict', use_embeddings: bool = True, *args, **kwargs):
```suggestion
    def __init__(self, executor: str = None, method: str = 'predict', fields: Union[str, Tuple[str]] = 'embedding', *args, **kwargs):
```

2021-02-18 06:38 UTC, nan-wang commented on jina/drivers/predict.py
> +            embed_vecs, docs_pts = docs.all_contents
What about using the same argument as in #1953? I think using other information besides `embedding` is potentially a general use case.  For this PR, raise an error and we implement the other functions in another PR.

```
if self.fields == 'embedding':
    ...
elif self.fields == 'content':
    ...
else:
    raise NotImplementedError
```

2021-02-18 07:38 UTC, rutujasurve94 commented on jina/drivers/predict.py
> +    """Drivers inherited from this Driver will bind :meth:`predict` by default
Instead of `this` driver use the class name `BasePredictDriver`. Nice work on this

2021-02-19 04:46 UTC, nan-wang requested changes
minor change. Let's use the singular format to be consistent with the field of `Document`.

Reference:
https://github.com/jina-ai/jina/blob/master/jina/types/document/__init__.py#L397
https://github.com/jina-ai/jina/blob/master/jina/types/document/__init__.py#L596

2021-02-19 04:46 UTC, nan-wang commented on jina/drivers/predict.py
> +        if self.fields == 'embeddings':
```suggestion
        if self.fields == 'embedding':
```

2021-02-19 04:46 UTC, nan-wang commented on jina/drivers/predict.py
> +        elif self.fields == 'contents':
```suggestion
        elif self.fields == 'content':
```

2021-02-24 02:28 UTC, nan-wang approved these changes
LGTM👍

2021-02-24 02:29 UTC, merged

2021-02-24 02:31 UTC, nan-wang commented
recheckcla