test(logging): add timedict test
jina-ai/jina pull request #1969
Opened 2021-02-18 03:58 UTC by Yongxuanzhang

2021-02-18 13:37 UTC, JoanFM requested changes

2021-02-18 13:37 UTC, JoanFM commented on tests/unit/logging/test_logging_profile.py
> +    assert int(td.accum_time["timer"]) == 2
can u please use `single quotes`? Otherwise, great job!

2021-02-18 14:15 UTC, Yongxuanzhang commented on tests/unit/logging/test_logging_profile.py
> +    assert int(td.accum_time["timer"]) == 2
Sure! Thanks!

2021-02-18 18:58 UTC, JoanFM approved these changes
LGTM!

2021-02-19 07:01 UTC, nan-wang approved these changes
LGTM👍

2021-02-19 07:01 UTC, merged