fix: update the resource file for BaseRankingEvaluator
jina-ai/jina pull request #1979
Opened 2021-02-19 05:39 UTC by nan-wang

fix: update the resource file for BaseRankingEvaluator

2021-02-19 08:24 UTC, florian-hoenicke commented
Can we have a small test or adjust an existing test?

2021-02-20 15:26 UTC, hanxiao requested changes
im not sure this is a valid change, `tags.id` is not always there unless you fill it. `BaseRankingEvaluator` should not depend on a field that not exist.

2021-02-24 08:45 UTC, nan-wang commented
@hanxiao @JoanFM @florian-hoenicke Instead of changing the resource file, I've just added a unit test to show the issue. 

In https://github.com/jina-ai/jina/blob/master/jina/drivers/evaluate.py#L124, we provide the default value for fields as `('tags__id',)`.

However, in the resource file, https://github.com/jina-ai/jina/blob/master/jina/resources/executors.requests.BaseRankingEvaluator.yml#L17, we provide the default value for fields as `['id']`. 

This inconsistency might introduce confusion for the users. I think Han's argument is valid, and therefore suggest to remove the default value in the resource file and change the default value in `RankEvaluateDriver` to `('id', )`

2021-02-24 11:57 UTC, cristianmtr commented on jina/drivers/evaluate.py
> +        :return: a list of tuples consisted of the values from the fields.
```suggestion
        :return: a list of tuples consisting of the values from the fields.
```

2021-02-24 14:54 UTC, nan-wang commented on jina/drivers/evaluate.py
> +        :return: a list of tuples consisted of the values from the fields.
good catch!

2021-02-25 07:18 UTC, JoanFM approved these changes

2021-02-25 08:45 UTC, merged