docs:  warn users about driver stored in executors
jina-ai/jina pull request #2111
Opened 2021-03-03 15:16 UTC by davidbp

2021-03-03 15:21 UTC, JoanFM commented on jina/executors/__init__.py
> +            want to store/load Executors be aware not to change the `.yaml` file after
I would specially talk about drivers.

2021-03-04 07:41 UTC, theUnkownName requested changes

2021-03-04 07:41 UTC, theUnkownName commented on jina/executors/__init__.py
> +            In particular, information regarthing `drivers` is serialized.
Typo in "regarding"

2021-03-04 07:41 UTC, theUnkownName commented on jina/executors/__init__.py
> +            file that set up `drivers` after loading, any change these parts will not take effect after serialization.
"any change *in* these parts" maybe?

2021-03-05 05:51 UTC, nan-wang requested changes
Rephrase it a little bit.

2021-03-05 05:51 UTC, nan-wang commented on jina/executors/__init__.py
> +            file that set up `drivers` after loading, any change these parts will not take effect after serialization.
```suggestion
            When you load a stored Executor, be aware not to change the driver settings in the  `.yaml` 
            file. Any change to the driver settings will not take effect after storing Executors.
```

2021-03-05 07:50 UTC, closed without merging