fix: avoid dump drivers
jina-ai/jina pull request #2133
Opened 2021-03-09 11:45 UTC by davidbp

2021-03-09 12:39 UTC, JoanFM requested changes

2021-03-09 12:39 UTC, JoanFM commented on tests/unit/executors/test_dump_executor_with_drivers.py
> +def test_dump_excutor_without_drivers(tmpdir):
typo in test nane

2021-03-09 16:06 UTC, JoanFM commented on jina/executors/__init__.py
> +        "encode",
is this black doing it?

2021-03-09 16:16 UTC, JoanFM requested changes

2021-03-09 16:16 UTC, JoanFM commented on jina/executors/__init__.py
> +__all__ = ["BaseExecutor", "AnyExecutor", "ExecutorType"]
we try to enforce single quote style

2021-03-10 08:24 UTC, davidbp commented on jina/executors/__init__.py
> +        "encode",
yes

2021-03-10 09:08 UTC, davidbp commented on jina/executors/__init__.py
> +__all__ = ["BaseExecutor", "AnyExecutor", "ExecutorType"]
done

2021-03-10 09:14 UTC, JoanFM requested changes

2021-03-10 09:14 UTC, JoanFM commented on jina/executors/__init__.py
> +        return self.get_file_from_workspace(f"{self.name}.bin")
single quote

2021-03-10 09:14 UTC, JoanFM commented on jina/executors/__init__.py
> +        return self.get_file_from_workspace(f"{self.name}.yml")
same here

2021-03-10 09:14 UTC, JoanFM commented on jina/executors/__init__.py
> +            os.path.join(workspace_folder, f"{workspace_name}-{pea_id}")
and here

2021-03-10 09:14 UTC, JoanFM commented on jina/executors/__init__.py
> +        return self.workspace or "./"
and here

2021-03-10 09:14 UTC, JoanFM commented on jina/executors/__init__.py
> +        return sum(f.stat().st_size for f in root_directory.glob("**/*") if f.is_file())
and here

2021-03-10 09:14 UTC, JoanFM commented on jina/executors/__init__.py
> +                    + f".snapshot-{self._last_snapshot_ts.strftime('%Y%m%d%H%M%S') or 'NA'}"
and here

2021-03-10 09:14 UTC, JoanFM commented on jina/executors/__init__.py
> +        if "metas" not in raw_config:
and here

2021-03-10 09:24 UTC, davidbp commented on jina/executors/__init__.py
> +        return self.get_file_from_workspace(f"{self.name}.bin")
updated

2021-03-10 09:25 UTC, JoanFM approved these changes

2021-03-10 09:46 UTC, florian-hoenicke approved these changes

2021-03-10 09:48 UTC, merged