test: regression test for all hello world examples
jina-ai/jina pull request #2205
Opened 2021-03-18 13:54 UTC by bwanglzu

WIP #2193

2021-03-19 05:33 UTC, JoanFM requested changes

2021-03-19 05:33 UTC, JoanFM commented on tests/system/fashion/test_fashion.py
> +            'granularity': 1,
granularity is 0 in this case

2021-03-19 05:33 UTC, JoanFM commented on tests/system/chatbot/test_chatbot.py
> +            'granularity': 1,
same here

2021-03-20 15:40 UTC, JoanFM requested changes

2021-03-20 15:40 UTC, JoanFM commented on tests/system/fashion/test_fashion.py
> +def test_query_image():
this is not used right?

2021-03-20 15:40 UTC, JoanFM commented on tests/system/fashion/test_fashion.py
> +def test_multimodal(helloworld_args, query_document, mocker):
the name of the test is not correct

2021-03-20 15:40 UTC, JoanFM commented on tests/system/fashion/test_fashion.py
> +    """Regression test for multimodal example."""
wrong annotation

2021-03-20 21:45 UTC, Yongxuanzhang reviewed
Very good test! Learned a lot! 😄

2021-03-21 02:52 UTC, bwanglzu commented
@JoanFM fixed

2021-03-21 05:37 UTC, rutujasurve94 commented on tests/system/fashion/test_fashion.py
> +def query_document(test_query_image):
`text_query_image` argument is not being used here

2021-03-21 13:04 UTC, merged