refactor: merge batching decorators
jina-ai/jina pull request #2269
Opened 2021-04-01 05:34 UTC by Kelton8Z

2021-04-01 06:34 UTC, JoanFM requested changes

2021-04-01 06:34 UTC, JoanFM commented on jina/executors/decorators.py
> +            copy_args = copy.copy(args)
is the copy needed? this can become quite expensive

2021-04-01 06:34 UTC, JoanFM commented on jina/executors/decorators.py
> +                    # TODO: figure out what is ordinal_idx_arg
check NmsLibIndexer in jina-hub to understand the feature

2021-04-01 06:34 UTC, JoanFM commented on tests/unit/executors/test_decorators.py
> +            print(f'ord_idx : {ord_idx}')
clean up this test

2021-04-01 06:34 UTC, JoanFM commented on tests/unit/executors/test_decorators.py
> +'''
remove if not used

2021-04-02 22:22 UTC, Yongxuanzhang reviewed
You can first create a draft PR to fix all the tests then open it.
Need to fix corresponding tests to adapt changes

2021-04-07 10:10 UTC, JoanFM approved these changes

2021-04-07 10:10 UTC, merged