test(flow): moved test_segmenter.py into a flow unittest
jina-ai/jina pull request #2287
Opened 2021-04-08 03:12 UTC by MiaAltieri

Flowed the suggestion in Issue 692 to move the tests in test_segmenter.py under flow tests and have the same functionality tested as a simple unittest. Cleaned up some of the duplicated code.

If you'd like to see something else or I've misunderstood please reach out.

2021-04-08 08:29 UTC, nan-wang requested changes
Would you please elaborate on the differences between `dummy-seg-not-random.yml` and `dummy-seg-random.yml`?

2021-04-08 08:29 UTC, nan-wang commented on tests/unit/flow/yaml/dummy-seg-not-random.yml
> +        method: segment
Here is the new convention of yaml
```suggestion
jtype: DummySegment
requests:
  use_default: true
```

2021-04-08 08:29 UTC, nan-wang commented
recheckcla

2021-04-09 00:23 UTC, MiaAltieri commented
My apologies, while adapting the code from its original source underneath `tests/integration/mime` I didn't check to see if the files `dummy-seg-not-random.yml` and `dummy-seg-random.yml` were in fact different. It appears they are the same, let me update the code to reflect that

2021-04-09 00:24 UTC, MiaAltieri commented
**_I have read the CLA Document and I hereby sign the CLA_**

2021-04-12 09:45 UTC, nan-wang submitted a review, later dismissed
LGTM👍

2021-04-12 09:51 UTC, nan-wang commented
@MiaAltieri Thanks for your contribution. However this PR does not pass our docstring and black checks. Please make sure you have the `precommit` properly set up locally. If you still have the same issue, you will need to either rebase your PR or create a new one. 

reference:
https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#-making-your-first-submission

2021-04-14 01:53 UTC, MiaAltieri commented
Hi I apologize for committing again without it passing both the docstring check and black. I thought I had done it correctly since black said it passed by reporting:
`black....................................................................Passed`
after I committed. Let me look into this more

2021-04-14 06:10 UTC, JoanFM commented
> Hi I apologize for committing again without it passing both the docstring check and black. I thought I had done it correctly since black said it passed by reporting the following after I committed:
> `black....................................................................Passed`
> Let me look into this more.
> 
> If you have any suggestions for things I could check let me know. I noticed that when I looked into the tests that failed on both black and check-dockstring (on git) they both say "Error: The head commit for this pull_request event is not ahead of the base commit. Please submit an issue on this action's GitHub repo." however when I looked at my forked repository it was up to date.
> 
> I can try rebasing/creating a new one

Hey @MiaAltieri , merging with master should be good enough

2021-04-15 15:44 UTC, MiaAltieri commented
Awesome, rebased into one commit and merged with master

2021-04-17 03:04 UTC, hanxiao approved these changes

2021-04-17 03:04 UTC, merged