feat: indexing works for hello-world
jina-ai/jina pull request #2377
Opened 2021-05-03 12:59 UTC by maximilianwerk

Be aware of the following change suggestions:

- add `__init__` back to the Executor and make the metaclass less magic. (e.g. requests and metas parsing)
- add fully computed workspace property to executor. That might also be moved into the ZED runtime and be pre-computed. Anyhow, we believe providing it on executor level is the right level of abstraction.
- fixed the `requests` decorator, such that you can do:

```
class MyExecutor(Executor):
    @requests(on='seach')
    def my_func(self, *args, **kwargs):
        pass

my_obj = MyExecutor()
my_obj.my_func() <--- did not work before
```

2021-05-03 13:42 UTC, hanxiao commented on jina/executors/__init__.py
> +        super().__init__()
```suggestion
```
unnecessary

2021-05-03 13:52 UTC, JoanFM requested changes

2021-05-03 13:52 UTC, JoanFM commented on jina/executors/__init__.py
> +    def __init__(self, metas=None, requests=None, *args, **kwargs):
type hinting

2021-05-03 13:52 UTC, JoanFM commented on jina/executors/indexers/dbms/keyvalue.py
> +    def write_handler(self):
let's use this refactoring to remove so much magic from this maybe?

2021-05-03 13:52 UTC, JoanFM commented on jina/executors/indexers/dbms/keyvalue.py
> +    def __getstate__(self):
this should be removed as no more dumping is happening.

2021-05-03 13:52 UTC, JoanFM commented on jina/executors/indexers/keyvalue.py
> +    def delete(self, keys: Iterable[str], *args, **kwargs) -> None:
this should receive `doc_array`

2021-05-03 13:52 UTC, JoanFM commented on jina/executors/indexers/keyvalue.py
> +    def _add(
same here

2021-05-03 13:52 UTC, JoanFM commented on jina/executors/indexers/dbms/keyvalue.py
> +    def add(self, docs: DocumentArray, *args, **kwargs):
`traversal_path` should be handled

2021-05-03 20:35 UTC, JoanFM commented
Isnt it missing the logic from VectorSearch and VectorIndexDriver?

2021-05-03 23:52 UTC, hanxiao commented
im taking this branch fixing what @JoanFM proposed and reverting back this change
> add __init__ back to the Executor and make the metaclass less magic. (e.g. requests and metas parsing)

The use of metaclass can't be fully removed and I don't want to add anymore boilerplate when subclassing an `Executor`.

2021-05-04 00:10 UTC, hanxiao commented on jina/executors/indexers/dbms/keyvalue.py
> +    def dump(self, parameters, *args, **kwargs) -> None:
this is wrong, arguments are passed in order. see https://github.com/jina-ai/jina/blob/devel-2.0/COOKBOOK.md#method-arguments

2021-05-04 00:22 UTC, hanxiao commented on jina/resources/fashion/helloworld.indexer.yml
> +jtype: BinaryPbDBMSIndexer
this looks unmatch with prev. I don't think the vector indexing is implemented.

2021-05-04 00:24 UTC, hanxiao commented
i will merge this PR but I don't think this matches the behavior of indexing at 1.x.

2021-05-04 00:26 UTC, merged

2021-05-04 02:56 UTC, hanxiao commented on jina/executors/__init__.py
> +        if requests is not None:
wrong logic here