feat: adapt sparse pipeline test to 2.0
jina-ai/jina pull request #2429
Opened 2021-05-17 05:09 UTC by Kelton8Z

2021-05-17 05:48 UTC, JoanFM requested changes

2021-05-17 05:48 UTC, JoanFM commented on tests/integration/sparse_pipeline/indexer.yml
> +  on:
this is not executor 2.0 API  Reviee the cookbook

2021-05-17 05:48 UTC, JoanFM commented on tests/integration/sparse_pipeline/test_sparse_pipeline.py
> +    def encode(self, content: 'np.ndarray', *args, **kwargs) -> Any:
this is old API

2021-05-17 05:48 UTC, JoanFM commented on tests/integration/sparse_pipeline/test_sparse_pipeline.py
> +    def query(self, vectors: 'scipy.sparse.csr_matrix', top_k: int, *args, **kwargs):
so is this

2021-05-17 09:30 UTC, JoanFM requested changes

2021-05-17 09:30 UTC, JoanFM commented on tests/integration/sparse_pipeline/test_sparse_pipeline.py
> +        self.docs = []
docs can then be a DocumentArray

2021-05-17 09:30 UTC, JoanFM commented on tests/integration/sparse_pipeline/test_sparse_pipeline.py
> +    def encode(self, docs: 'DocumentArray', *args, **kwargs) -> Any:
this will not work to have 2 methods with the same request. Maybe have a single privat encode method that u call from add and search

2021-05-17 09:30 UTC, JoanFM commented on tests/integration/sparse_pipeline/test_sparse_pipeline.py
>          # avoid creating dump, do not polute workspace
then just delete

2021-05-18 03:50 UTC, Kelton8Z commented on tests/integration/sparse_pipeline/test_sparse_pipeline.py
>          # avoid creating dump, do not polute workspace
oh right, since there's no more inheritance

2021-05-18 06:03 UTC, Kelton8Z commented
commit history messed up during merging of master and devel-2.0

2021-05-18 06:03 UTC, closed without merging