feat: add example of executor using fastapi
jina-ai/jina pull request #2477
Opened 2021-05-25 14:10 UTC by davidbp

Add Executor leveraging fast api to encode images

2021-05-25 14:14 UTC, Yongxuanzhang reviewed
the title should be fastai?

2021-05-25 14:16 UTC, davidbp commented
> the title should be fastai?

sure, thanks!

2021-05-25 14:17 UTC, davidbp commented on .github/2.0/cookbooks/Executor.md
> +             batch_images.append(doc.blob)
We could, but .. is there any need or you mean it should be the default way to do it?

2021-05-25 14:30 UTC, JoanFM commented on .github/2.0/cookbooks/Executor.md
> +             batch_images.append(doc.blob)
let's do it since it will be shorter

2021-05-25 14:34 UTC, davidbp commented on .github/2.0/cookbooks/Executor.md
> +             batch_images.append(doc.blob)
done

2021-05-25 14:46 UTC, JoanFM requested changes

2021-05-25 14:46 UTC, JoanFM commented on .github/2.0/cookbooks/Executor.md
> +         batch_embeddings = self.model(batch)
this does not make much sense.  Shouldn't this be
`
batch_embeddings = self.model(batch).detach().numpy()
for doc, embedding in zip(docs, batch_embeddings)

`

2021-05-25 14:56 UTC, JoanFM requested changes
I think also u can move the import of `fastai` on top. The need to hide the imports is not anymore there

2021-05-26 09:04 UTC, JoanFM approved these changes

2021-05-26 09:04 UTC, JoanFM commented on .github/2.0/cookbooks/Executor.md
> +=======
remove this line coming from some bad merge

2021-05-26 09:43 UTC, JoanFM approved these changes

2021-05-26 09:50 UTC, davidbp commented on .github/2.0/cookbooks/Executor.md
> +This `Executor` uses the [ResNet18](https://docs.fast.ai) network for object classification on images provided by [fastai](https://github.com/fastai/fastai).
I like it more the way it is, it is not a label I populate. It is a vector of activations (same is done in the Pytorch Executor).

2021-05-26 11:31 UTC, JoanFM approved these changes

2021-05-26 11:31 UTC, merged