test: added a test for docmatrix in the tail pea
jina-ai/jina pull request #2537
Opened 2021-06-01 11:59 UTC by maximilianwerk

This is a test showcasing, how a `MatchMerger` in a TailPea could look like. Beware, that replica/sharding for `(1,2)` and `(2,1)` are broken. That needs to be fixed before 2.0 release.

2021-06-01 12:17 UTC, cristianmtr approved these changes

2021-06-01 12:18 UTC, JoanFM commented
(1, 2) should work now.

What I am not sure about with `replicas`. Right now the `HeadPea` or `TailPea` of a `CompoundPod` are not equipped with anything (which is an assumption of the polling types)

2021-06-01 12:30 UTC, JoanFM requested changes

2021-06-01 12:30 UTC, JoanFM commented on tests/integration/v2_api/test_docs_matrix_tail_pea.py
> +@pytest.mark.parametrize('replicas_shards', [(1, 1), (2, 2)])
```suggestion
@pytest.mark.parametrize('replicas, shards', [(1, 1), (2, 2)])
def test_sharding_tail_pea(nu,m_replicas, num_shards):
```

I think this works better and u do not need to separate

2021-06-02 06:24 UTC, maximilianwerk commented on scripts/black.sh
> +   tests/
Why?

2021-06-02 06:26 UTC, JoanFM commented on scripts/black.sh
> +   tests/
I agree with Max, I like having them beautified

2021-06-02 09:09 UTC, cristianmtr commented on tests/integration/v2_api/test_docs_matrix_tail_pea.py
> +    """TODO(Maximilian): Make (1, 2) and (2, 1) also workable"""
opened an issue for this https://github.com/jina-ai/jina/issues/2547

2021-06-02 09:09 UTC, cristianmtr approved these changes

2021-06-02 09:27 UTC, merged