refactor: remove Peatype metaclass
jina-ai/jina pull request #2688
Opened 2021-06-17 08:00 UTC by JoanFM

2021-06-17 08:32 UTC, deepankarm commented on jina/logging/logger.py
> +            self.success
`lambda` is not picklable, but `partial` is, so we can use partial too

2021-06-18 08:10 UTC, JoanFM commented
When `joining``a gateway Pea with spawn method:

I see this weird error:

```
Error in sys.excepthook:

Original exception was:
```

2021-06-18 08:13 UTC, JoanFM commented
I think I am observing this https://github.com/rapidsai/ucx-py/issues/468

2021-06-21 04:34 UTC, nan-wang submitted a review, later dismissed
In general, LGTM

2021-06-21 04:34 UTC, nan-wang commented on jina/peapods/peas/__init__.py
> +    def _cancel_rumtime(self):
```suggestion
    def _cancel_runtime(self):
```

2021-06-21 04:34 UTC, nan-wang commented on jina/peapods/runtimes/base.py
> +        2. :meth:`run_forever`. Note that this will block ``S``, step 3 won't be
Change the number here
```suggestion
        1. :meth:`run_forever`. Note that this will block ``S``, step 3 won't be
```

2021-06-21 04:34 UTC, nan-wang commented on jina/peapods/runtimes/zmq/zed.py
> +        super().__init__(*args, **kwargs)
It seems unnecessary.

2021-06-21 06:24 UTC, nan-wang requested changes
minor change request.

2021-06-21 06:24 UTC, nan-wang commented on jina/peapods/peas/__init__.py
> +        self._zed_runtime_ctrl_addres = Zmqlet.get_ctrl_address(
```suggestion
        self._zed_runtime_ctrl_address = Zmqlet.get_ctrl_address(
```

2021-06-21 06:32 UTC, JoanFM commented on jina/peapods/peas/__init__.py
> +        self._zed_runtime_ctrl_addres = Zmqlet.get_ctrl_address(
Thanks, done!

2021-06-21 06:37 UTC, nan-wang approved these changes
LGTM👍

2021-06-21 06:51 UTC, merged