fix: remove complain from ide
jina-ai/jina pull request #2720
Opened 2021-06-21 12:59 UTC by JoanFM

2021-06-21 13:54 UTC, hanxiao requested changes
there is no "GatewayPod"

2021-06-21 13:56 UTC, JoanFM commented on jina/peapods/pods/__init__.py
> +            'Set routing graph should only be called for `GateWayPod`'
```suggestion
            'Set routing graph should only be called for `Pod`'
```

2021-06-22 03:09 UTC, hanxiao commented
IDE complains of what?

2021-06-22 03:41 UTC, hanxiao commented
simply `self._pod_nodes = OrderedDict()  # type: Dict[str, Pod]`

2021-06-22 04:31 UTC, JoanFM commented
> IDE complains of what?

that BasePod does not have a set routing Graph method. Strictly speaking a CompoundPod instance could be part of the Flow and does not have it implemented.

2021-06-22 06:23 UTC, hanxiao commented
this function has been removed completely in https://github.com/jina-ai/jina/pull/2726 and move to inline

2021-06-22 06:26 UTC, closed without merging