fix(daemon): fix flexible root workspace mount in docker
jina-ai/jina pull request #2799
Opened 2021-06-29 10:49 UTC by jacobowitz

This fixes https://github.com/jina-ai/jina/issues/2768

JinaD now basically checks the host directory used for mounting its root workspace and will use the correct one when creating child containers (flow/peads/pods/.jinad). Before we were always mounting /tmp/jinad, which can be wrong if the user changes it.

I've added a test for this using docker compose, because I cant use the regular jinad instance as I need to control the volume mounting in other to test the correct thing here. This feels a bit akward there, but the test itself is okay and workling locally.

2021-06-29 17:11 UTC, deepankarm approved these changes

2021-06-30 10:07 UTC, deepankarm commented on .github/workflows/ci.yml
> +    env:
Please remember to make this change in cd.yml too.

2021-07-01 09:07 UTC, jacobowitz commented
rebased against https://github.com/jina-ai/jina/pull/2824 to check for test_common ci test failure

2021-07-01 10:29 UTC, jacobowitz commented
rebased against master now as https://github.com/jina-ai/jina/pull/2824 got merged

2021-07-01 10:30 UTC, jacobowitz commented
I think tests are fine, the only failure is flaky  tests/integration/rolling_update/

2021-07-01 10:42 UTC, deepankarm requested changes
Please remove `echo "JINA_DAEMON_BUILD=DEVEL" >> $GITHUB_ENV` from cd.yml:L246

2021-07-01 10:47 UTC, deepankarm approved these changes

2021-07-01 11:08 UTC, JoanFM approved these changes

2021-07-01 13:53 UTC, hanxiao approved these changes

2021-07-01 13:53 UTC, merged

2021-07-02 02:56 UTC, soljarjb13 reviewed
?

2021-07-02 02:56 UTC, soljarjb13 reviewed
?

2021-07-02 02:57 UTC, soljarjb13 reviewed
?

2021-07-02 02:57 UTC, soljarjb13 reviewed
?

2021-07-02 02:57 UTC, soljarjb13 reviewed
?