fix(hubio): when error occurs, exit code should be set to non-zero
jina-ai/jina pull request #2871
Opened 2021-07-07 06:51 UTC by mapleeit

2021-07-07 13:35 UTC, hanxiao requested changes
hub test is broken

2021-07-09 03:28 UTC, mapleeit commented
Ready to be review again. @hanxiao @numb3r3

2021-07-09 03:41 UTC, numb3r3 approved these changes

2021-07-09 07:11 UTC, JoanFM approved these changes

2021-07-09 08:58 UTC, hanxiao requested changes
just to clarify, this line assumes that `push` is always used under CLI, and it will invalidate the usage from other Python functions.

2021-07-09 09:10 UTC, merged