feat: raise exception when docker version is below 20.0.0
jina-ai/jina pull request #2895
Opened 2021-07-08 13:22 UTC by alaeddine-13

2021-07-08 13:40 UTC, JoanFM requested changes

2021-07-08 13:40 UTC, JoanFM commented on jina/peapods/runtimes/container/__init__.py
> +        docker_version = client.version().get("Version")
please use `single quotes`

2021-07-08 13:41 UTC, JoanFM commented
Why is this then not shown in the `extra-requirements.txt`?

2021-07-08 14:21 UTC, alaeddine-13 commented
> Why is this feature required?

When I was trying to run an executor with jinahub, I receive
```
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.40/containers/create?name=pod0ContainerRuntime: Bad Request ("invalid IP address in add-host: "host-gateway"")
```
Upgrading docker's version from 19 to 20 solves the issue

2021-07-08 14:37 UTC, JoanFM commented
> > Why is this feature required?
> 
> When I was trying to run an executor with jinahub, I receive
> 
> ```
> docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.40/containers/create?name=pod0ContainerRuntime: Bad Request ("invalid IP address in add-host: "host-gateway"")
> ```
> 
> Upgrading docker's version from 19 to 20 solves the issue

I think we should understand what's wrong and what exact version is solving this. I think the reason that bumping version solved this is not so strong.

2021-07-08 15:09 UTC, alaeddine-13 commented
> > > Why is this feature required?
> > 
> > 
> > When I was trying to run an executor with jinahub, I receive
> > ```
> > docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.40/containers/create?name=pod0ContainerRuntime: Bad Request ("invalid IP address in add-host: "host-gateway"")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Upgrading docker's version from 19 to 20 solves the issue
> 
> I think we should understand what's wrong and what exact version is solving this. I think the reason that bumping version solved this is not so strong.

I found this issue where they discuss the problem
https://github.com/docker/cli/issues/2664
According to it, the 20.0x versions of the docker daemon support `host.docker.internal:host-gateway`

2021-07-08 15:25 UTC, JoanFM commented
> > > > Why is this feature required?
> > > 
> > > 
> > > When I was trying to run an executor with jinahub, I receive
> > > ```
> > > docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.40/containers/create?name=pod0ContainerRuntime: Bad Request ("invalid IP address in add-host: "host-gateway"")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Upgrading docker's version from 19 to 20 solves the issue
> > 
> > 
> > I think we should understand what's wrong and what exact version is solving this. I think the reason that bumping version solved this is not so strong.
> 
> I found this issue where they discuss the problem
> [docker/cli#2664](https://github.com/docker/cli/issues/2664)
> According to it, the 20.0x versions of the docker daemon support `host.docker.internal:host-gateway`

Good finding then! Let's do this!

2021-07-08 15:25 UTC, JoanFM commented
> > > > Why is this feature required?
> > > 
> > > 
> > > When I was trying to run an executor with jinahub, I receive
> > > ```
> > > docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.40/containers/create?name=pod0ContainerRuntime: Bad Request ("invalid IP address in add-host: "host-gateway"")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Upgrading docker's version from 19 to 20 solves the issue
> > 
> > 
> > I think we should understand what's wrong and what exact version is solving this. I think the reason that bumping version solved this is not so strong.
> 
> I found this issue where they discuss the problem
> [docker/cli#2664](https://github.com/docker/cli/issues/2664)
> According to it, the 20.0x versions of the docker daemon support `host.docker.internal:host-gateway`

May u reference this issue in the code or even in the `raised exception`?

2021-07-09 07:30 UTC, JoanFM approved these changes

2021-07-09 08:41 UTC, merged