feat: add local flow use remote executor test
jina-ai/jina pull request #2954
Opened 2021-07-15 07:55 UTC by bwanglzu

2021-07-15 13:51 UTC, JoanFM requested changes

2021-07-15 13:51 UTC, JoanFM commented on tests/distributed/test_local_flow_use_remote_executor/docker-compose.yml
> +    entrypoint: "jina executor --uses jinahub+docker://CLIPImageEncoder --port-in 45678 --socket-in ROUTER_BIND --dynamic-routing-out"
jinahub://CLIPImageEncoder cannot be a dependency of the `test`. There is no need to test this specific executor. U can create one if u want for the test but is overkill

2021-07-15 15:30 UTC, JoanFM commented
@bwanglzu according to @deepankarm this will not be able to work now.

2021-07-23 12:07 UTC, bwanglzu commented
close since it has been done in another PR.

2021-07-23 12:07 UTC, closed without merging