feat: connect to pred config
jina-ai/jina pull request #3051
Opened 2021-07-30 08:52 UTC by maximilianwerk

This allows to overwrite our remote-local detection magic explicitly for special use-cases (e.g. running on multiple instances in a VPN and additionally having one remote Pod).

2021-08-02 08:05 UTC, JoanFM reviewed
When we were trying to have remote external Pods it was very hard to understand what are the needed arguments related to `dynamic` routing. I am not sure if this adds yet more noise to this.

In which context have we encountered this need?

2021-08-02 08:06 UTC, JoanFM requested changes

2021-08-02 08:06 UTC, JoanFM commented on cli/autocomplete.py
> +            '--no-dynamic-routing',
it makes not much sense to have these 2 options at the same time and redundant

2021-08-02 08:07 UTC, JoanFM commented on jina/parsers/peapods/pod.py
> +    parser.add_argument(
How can this and the other coexits and be true by default?

2021-08-02 08:12 UTC, maximilianwerk commented
> When we were trying to have remote external Pods it was very hard to understand what are the needed arguments related to `dynamic` routing. I am not sure if this adds yet more noise to this.
> 
> In which context have we encountered this need?

We are preparing a Cookbook section for explaining how to setup hosts correctly. This PR is a pre-step for it in order to remove make the setup easier with this Cookbook.

2021-08-02 13:54 UTC, maximilianwerk commented
@JoanFM the cookbook will be changed in #3066

2021-08-03 13:13 UTC, JoanFM approved these changes

2021-08-03 13:24 UTC, merged