refactor: change bind to all inbound
jina-ai/jina pull request #3069
Opened 2021-08-02 11:49 UTC by slettner

This PR introduces the following change:

For all runtimes, the gateway will bind to all inbound connections on the localhost, i.e. `0.0.0.0` instead of the parameter `args.host`. 

This change is motivated by a use-case from kubernetes where the gateway host deployment is hidden behind a kubernetes service with corresponding dns (this is a typical kubernetes pattern). 
Clients can reach the gateway via this dns from the outside but the host cannot bind to this address as it is the IP of the service not the deployment where the gateway runs.

2021-08-02 13:55 UTC, maximilianwerk commented
@JoanFM @deepankarm any objections?

2021-08-02 14:23 UTC, JoanFM commented
it seems good. It surprises me how it used to work before? Binding is always local to one self right?

2021-08-02 14:50 UTC, JoanFM commented
What I do not understand is then why `uvicorn` exposes the `host` argument.

In the meanwhile, u can simply set properly the `host` argument right @slettner .

I would wait for @deepankarm input on this

2021-08-02 14:50 UTC, JoanFM requested changes
Wait for @deepankarm input

2021-08-03 01:51 UTC, hanxiao commented
>  It surprises me how it used to work before? Binding is always local to one self right?

Because `arg.host` by default is `0.0.0.0`

Note that this PR is not complete, if in those contexts `host` is no longer a parameter, then argparse should not expose them to the users. The parser side needs to be refactored a bit to remove `host` for those context.

2021-08-03 07:39 UTC, maximilianwerk commented
> > It surprises me how it used to work before? Binding is always local to one self right?
> 
> Because `arg.host` by default is `__default_host__`
> 
> Note that this PR is not complete, if in those contexts `host` is no longer a parameter but a constant, then `argparse` should not expose them to the users. The parser side needs to be refactored a bit to remove `host` for those context.

That's wrong. We still need the `host` to tell the last Pod how to reach the Gateway again. For this, we need to configure the host of the Gateway. With dynamic routing, you never define `host_in` and `host_out` by yourself, but only tell each Pod on which host it runs. The Flow then computes the relevant information for either the `routing_table` or sets `host_in` if we have a remote-local situation.

2021-08-03 07:43 UTC, maximilianwerk commented
To give some more motivation, imagine the following Flow:

```
Flow.add(name='p1').add(name='p2').add(name='p3', needs=['p1', 'p2'])
```

You can now easily put them on different machines via setting `host` of each Pod. Anyhow, if you want to configure the `host_in` of `p3`, what would it be - `p1.host` or `p2.host`? Same holds true for `host_out` of `p1` - `p2.host` or `p3.host`?

2021-08-03 07:55 UTC, hanxiao commented
> The parser side needs to be refactored a bit to remove host for those context.

`context` means every context mentioned in this PR. Not beyond this PR.

2021-08-03 08:18 UTC, maximilianwerk commented
> > The parser side needs to be refactored a bit to remove host for those context.
> 
> `context` means every context mentioned in this PR. Not beyond this PR.
> 
> Every parser behind these `contexts` should remove `host` as argument. Any parser that not related to this PR should stay the same.

The `host` argument is currently used in four places:

- `Daemon` => still needed
- `Pea` => still needed
- `Gateway` => still needed as described above
- `ClientCLI` => still needed or at least this PR does not change anything with the `ClientCLI`

The Gateway also uses the `mixin_http_gateway_parser`, which actually does not has the `host` argument and thus, we don't need to change anything. Perhaps this should have had the `host` argument beforehand, but it does not. `GRPC` and `websocket` do not have their own mixins at all.

Am I getting you right, if you would prefer to split the configuration into further mixins with these arguments specified more detailed and as low level as possible?

2021-08-03 08:57 UTC, JoanFM approved these changes

2021-08-03 12:41 UTC, merged