feat(hubble): push/pull rich logging
jina-ai/jina pull request #3104
Opened 2021-08-04 14:06 UTC by numb3r3

2021-08-06 02:31 UTC, mapleeit approved these changes

2021-08-06 02:37 UTC, winstonww approved these changes

2021-08-06 02:39 UTC, mapleeit commented
Pulling:

<img width="635" alt="Screen Shot 2021-08-06 at 10 37 25 AM" src="https://user-images.githubusercontent.com/4194287/128447564-e553ba14-41f4-4cf6-90de-29b14c0f12d4.png">

Pushing:

<img width="577" alt="Screen Shot 2021-08-06 at 10 38 45 AM" src="https://user-images.githubusercontent.com/4194287/128447692-c2061812-d763-4223-bd26-9f30b2fe2fca.png">

2021-08-06 07:01 UTC, JoanFM requested changes

2021-08-06 07:01 UTC, JoanFM commented on jina/hubble/hubio.py
> +                            if status_id not in tasks:
this is not safe if status_id is None

2021-08-06 07:01 UTC, JoanFM commented on jina/hubble/hubio.py
> +                            if pg_detail:
```suggestion
                            if pg_detail is not None:
```

2021-08-06 07:01 UTC, JoanFM commented on jina/hubble/hubio.py
> +                                task = tasks[status_id]
what if `status_id` is None

2021-08-06 07:01 UTC, JoanFM commented on jina/hubble/hubio.py
> +                            True for _ in pkg_dist_path.glob('PKG-SN-*')
I am not sure if `True` is needed here

2021-08-06 07:22 UTC, numb3r3 commented on jina/hubble/hubio.py
> +        try:
Thanks for your remind. With manually test, the ctx also raises the exception to the outside

2021-08-06 07:40 UTC, numb3r3 commented
@JoanFM thanks for your comments. I made a new commit to address them. To make it safe to work with `status_id=None` or `pg_detail = None`, I add if condition checking at the beginning.

2021-08-09 07:54 UTC, JoanFM approved these changes

2021-08-09 08:22 UTC, merged