feat: add data request handler
jina-ai/jina pull request #3105
Opened 2021-08-04 14:42 UTC by JoanFM

2021-08-04 14:47 UTC, JoanFM commented
https://github.com/jina-ai/internal-tasks/issues/141

2021-08-04 15:19 UTC, jacobowitz requested changes
Thx for the change!
I have one minor naming suggestion and a question regarding the runtime design relating to those self.message etc fields

2021-08-04 15:19 UTC, jacobowitz commented on jina/peapods/runtimes/zmq/zed.py
> +        self.data_request_handler = DataRequestHandler(self.args, self.logger)
private?

2021-08-04 15:21 UTC, JoanFM commented on jina/peapods/runtimes/zmq/zed.py
> +            request=self.request,
I  would agree, it puts state into the `runtime` which would be very dangerous for ur new runtime which would not be blocking and async

2021-08-05 10:02 UTC, jacobowitz approved these changes
lgtm, some tests seem to be failing though

2021-08-05 14:12 UTC, jacobowitz approved these changes
very nice refactoring :+1:

2021-08-05 21:21 UTC, merged