fix: no warning for metas in executor
jina-ai/jina pull request #3219
Opened 2021-08-19 06:51 UTC by maximilianwerk

If you use `metas` inside an Executor definition, there was a warning, that it is an unknown argument beforehands. Even thought it is not really used inside the argparse, this is the correct way in my opinion.

2021-08-19 11:23 UTC, maximilianwerk commented
Can I get some opinions here, if that makes sense. So the point is:

`metas` is used as an argument for Peas. If we check for known/unknown arguments the parser is the source of truth. Thus, if we are able to specify `metas` it should consequently also be a parameter, non?

@JoanFM @deepankarm @hanxiao

2021-08-19 12:10 UTC, JoanFM commented
I am not sure what's the strategy. I think having the metas defined in the `executor` config is more handy that having it in the `Flow` yaml.

2021-08-19 12:41 UTC, hanxiao requested changes
i need time to figure out why this is necessary, will come back later

2021-08-19 13:04 UTC, maximilianwerk commented
> i need time to figure out why this is necessary, will come back later

Following line of thought:

The general target of `warn_unknown_args` is to give the user a warning they use a not-existing or deprecated argument. This is usually done via checking the `unknown_args` returning from `argparse`. If `metas` is only used somewhere hidden without defined as a proper argument, it will always be treated as an unknown argument. Since we anyhow rely on the power of argparse, all user defined arguments should be represented by one parser or another.

I am not sure, if I 100% agree with this line of thought above, but users complained, that they did not got any warning, when specifying deprecated arguments. So this was my idea of solving it: Get more rigid with arg parsing.

2021-08-19 19:36 UTC, hanxiao commented
the test is incorrect, that YAML in the test is not a valid Flow anyway.

You may want to use the below instead, which gives a valid Flow with one executor and executor has metas 

```python
yaml = '''jtype: Flow
version: 1
executors:
    - uses: 
        jtype: BaseExecutor
        metas:
            name: hello
    '''
with Flow().load_config(yaml):
    pass
```

which gives no warning.

2021-08-20 13:59 UTC, jacobowitz approved these changes

2021-08-20 14:00 UTC, merged