fix(dam): warning truncate doc id
jina-ai/jina pull request #3264
Opened 2021-08-25 07:51 UTC by numb3r3

address https://github.com/jina-ai/jina/issues/3260

2021-08-25 07:55 UTC, hanxiao requested changes
this behavior is not memmap specific

2021-08-25 08:00 UTC, JoanFM commented
@hanxiao no other object has this key length.

2021-08-25 09:30 UTC, alaeddine-13 commented
LGTM

2021-08-28 09:21 UTC, hanxiao approved these changes

2021-08-28 09:21 UTC, merged