Feat lsh
jina-ai/jina pull request #3300
Opened 2021-08-30 18:46 UTC by kingkonk81

A prototype implementation of locality sensitive hashing for fast similarity search.

2021-08-31 08:55 UTC, bwanglzu commented
hi @kingkonk81 thanks so much for contributing! However we need more discussion on that, should LSH part of core or an executor, and the implementation might have performance issue, need more benchmarking. If possible can you create an issue, raise some discussion first then go to the real implementation?

2021-08-31 09:08 UTC, bwanglzu commented
@kingkonk81 we decided to not add LSH into jina core, but jina executors. Are you interested in raise a PR in [executor repo](https://github.com/jina-ai/executors)?

2021-08-31 16:12 UTC, kingkonk81 commented
Hello Wang,

This was a "fake pull request" as part of my application for the machine
learning scientist position.

I don't think that creating an executor would be right way for doing LSH.
At a high level we need to create an inverted index for documents that
allows fast retrieval of candidate documents. With my (rather limited)
understanding of Jina, I would say this should go into Document and
DocumentArray. Each document should have a bucket id, similarly to its id
but the number of buckets will be much smaller than the number of
documents. The DocumentArray class should support efficient queries of the
form: "Give me all documents that belong to bucket <bucket id>." The latter
would involve a method that creates a dictionary with buckets as keys and
document ids in each bucket as values. This is similar to
_update_id_to_index_map(self) which, as written in the method
documentation, is costly. Also, other methods will need to be updated like
the ones for deletion and insertion, and new methods created.

As you see this would require discussions and planning with your engineers
as it goes into the core of Jina. And I don't know if you would be at all
interested in having an indexing scheme like this one. Moreover, there are
other options for fast similarity retrieval. I can create an issue if you
would like to have a more formal discussion on the topic.

Best,
Konstantin

On Tue, Aug 31, 2021 at 12:08 PM Wang Bo ***@***.***> wrote:

> @kingkonk81 <https://github.com/kingkonk81> we decided to not add LSH
> into jina core, but jina executors. Are you interested in raise a PR in executor
> repo <https://github.com/jina-ai/executors>?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jina-ai/jina/pull/3300#issuecomment-909048195>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFKV4EBWN2Q3ATEHMDXO63T7SLYXANCNFSM5DCOWA6A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-01 08:12 UTC, bwanglzu requested changes
hi @kingkonk81 I left some comments in the PR. And as discussed, this won't be able to merge into master. Sorry I miss some context before, now I knows.

In general, my feeling is that the code quality needs to be improved. No unitest, lack of docstrings, sometimes code is a bit difficult to read. From functional point of view, we might needs some explanation text in PR that indicates locally sensitive hashing works better than current implementation, with some figures etc. 

Before proving it works, we should not touch helloworld examples, since this is the first thing a user will do when they download Jina.

For the inverted index part. Maybe we need a inverted index at some point, I'm not sure about your idea on implementing it inside `Document` and `DocumentArray`. As far as I can imaging, it should be a separate thing.

2021-09-01 08:12 UTC, bwanglzu commented on jina/math/lsh.py
> +        bins = [{} for _ in range(nr_perms)]
`defaultdict` is a better choice: https://docs.python.org/3/library/collections.html

2021-09-01 08:12 UTC, bwanglzu commented on jina/parsers/helloworld.py
> +        help='Use locality sensitive hashing for nearest neighbor search'
same, do not touch until proven it works.

2021-09-01 08:12 UTC, bwanglzu commented on jina/types/arrays/neural_ops.py
> +            raise Exception("Not implemented")
never use `Exception`, use `NotImplementedError`

2021-09-20 10:14 UTC, JoanFM commented
I think this LSH should go into a specific executor, where an Indexer based on `DocumentArray` is built using LSH

2021-09-26 16:35 UTC, JoanFM commented
Hello @konstantinkutzkov ,

This sort of behavior should be moved into some specific `Executor`. You are more than welcome to push such an `Executor` to our hub with this implementation.

Thanks for the contribution

2021-09-26 16:35 UTC, closed without merging