Issuue 1
jina-ai/jina pull request #3332
Opened 2021-09-02 13:14 UTC by anuragdw710

2021-09-02 14:37 UTC, bwanglzu commented
can you give a descriptive title and PR description?

2021-09-06 07:57 UTC, jacobowitz requested changes
Hi @anuragdw710 
Thank you for our PR!
As @bwanglzu said: Please make sure to give the PR a proper title and description. Please also link any issue if there exists one. Please also read our guide on how to [contribute to Jina](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md)

And also please make sure that this change is covered by tests :)

2021-09-06 07:57 UTC, jacobowitz commented on daemon/clients/base.py
> +        self.timeout = timeout
You are effectively removing the timeout usage in your PR, why is that?

2021-09-06 07:57 UTC, jacobowitz commented on daemon/clients/base.py
> +        """Send delete request to api
Please be a bit more specific here

2021-09-08 06:50 UTC, jacobowitz commented
The PR looks stale to me, will close it for now. @anuragdw710 please feel free to reopen if you want to address the feedback.

2021-09-08 06:50 UTC, closed without merging