feat(util): add get_docs_batch_generator for documentarray
jina-ai/jina pull request #3386
Opened 2021-09-10 19:13 UTC by agarwalrounak

This PR aims to add `get_docs_batch_generator` for DocumentArray. This change would enable us to eliminate jina commons requirement from a lot of executors. 

The existing import statement `from jina_commons.batching import get_docs_batch_generator` in executors can be updated to `from jina.util import get_docs_batch_generator`. Another way could be to add `from jina.util import get_docs_batch_generator` to `jina/__init__.py` file and update the existing import statement in executors to `from jina import get_docs_batch_generator`.

2021-09-11 13:08 UTC, hanxiao requested changes
`.batch` should be a method of `DocumentArray` & `DocumentArrayMemap`

2021-09-11 13:38 UTC, agarwalrounak commented
Hi @hanxiao, thank you for your review! 
I had a query. By _**`.batch` should be a method of `DocumentArray` & `DocumentArrayMemap`**_, do you mean that add a method `batch` to the classes `DocumentArray` & `DocumentArrayMemap`, which then calls the `get_docs_batch_generator` method added in `util/__init__.py`? Please let me know if I understood it correctly.

2021-09-12 06:40 UTC, hanxiao commented
> By doing so, we would then be able to change the occurrences of get_docs_batch_generator(...) in executors to DocumentArray.batch(...) or DocumentArrayMemap.batch(...)

Yes, that would be the user experience.

I would suggest to implement `.batch` in `jina/types/arrays/traversable.py:TraversableSequence` mixin, as this mixin class is shared by both `DocumentArray` and `DocumentArrayMemap`.

2021-09-13 18:41 UTC, agarwalrounak commented
Thank you for your suggestion. I have implemented `batch` method in `TraversableSequence` mixin class. `batch` calls `get_docs_batch_generator` method added in `util/__init__.py` and returns the `Generator` created.

2021-09-14 19:51 UTC, hanxiao commented on jina/types/arrays/traversable.py
> +    @staticmethod
can you simply move `get_docs_batch_generator` function into `.batch` and make `.batch` **not** staticmethod?

The reason is that `DocumentArray` to jina is like `ndarray` to numpy, it is our basic data type, and we'd like to have any method that relate to `DocumentArray` or `DocumentArrayMemmap` as its "native" class method. We do not prefer "misc"/"util" module to store orphan methods, it is not part of our design. In Jina, every method should have a clear parent (at least to the best reasonable effort).

2021-09-14 19:52 UTC, hanxiao commented on jina/util/__init__.py
> +"""Module for Jina helper functions for batching documents in executors."""
Delete this file.

In general, we do not prefer some "misc"/"util" module to store orphan methods, it is not part of our design. In Jina, every method should have a clear parent (at least to the best reasonable effort).

2021-09-14 19:54 UTC, hanxiao requested changes
- move `get_docs_batch_generator` inside `jina/types/arrays/traversable.py` and **un-**staticmethod the `.batch` func
- need unit tests

2021-09-18 10:20 UTC, closed without merging

2021-09-20 06:06 UTC, agarwalrounak commented
@hanxiao I was away from my laptop for a while, so I couldn't work on the changes you suggested. Sorry for that! I see that you opened a new PR with the changes. 
I will pick up a different issue to work on.