feat: add setters and getters for da and dam
jina-ai/jina pull request #3418
Opened 2021-09-15 18:23 UTC by tadejsv

This adds setter and getter methods for DA and DAM, for `texts` and `tags`

2021-09-16 03:44 UTC, numb3r3 requested changes

2021-09-16 03:44 UTC, numb3r3 commented on jina/types/arrays/memmap.py
> +        return self.get_attributes('tags')
```suggestion
        return self.get_attributes('texts')
```

2021-09-20 11:32 UTC, alaeddine-13 approved these changes
LGTM, just minor fixes

2021-09-20 11:32 UTC, alaeddine-13 commented on tests/unit/types/arrays/test_memmap.py
> +def test_tags_getter_da(tmpdir):
```suggestion
def test_tags_getter_dam(tmpdir):
```

2021-09-20 11:32 UTC, alaeddine-13 commented on tests/unit/types/arrays/test_memmap.py
> +def test_tags_setter_da(tmpdir):
```suggestion
def test_tags_setter_dam(tmpdir):
```

2021-09-20 11:32 UTC, alaeddine-13 commented on tests/unit/types/arrays/test_memmap.py
> +def test_texts_getter_da(tmpdir):
```suggestion
def test_texts_getter_dam(tmpdir):
```

2021-09-20 11:32 UTC, alaeddine-13 commented on tests/unit/types/arrays/test_memmap.py
> +def test_texts_setter_da(tmpdir):
```suggestion
def test_texts_setter_dam(tmpdir):
```

2021-09-20 14:50 UTC, hanxiao approved these changes

2021-09-20 14:50 UTC, merged