fix(k8s): Do not hard code the FQDN
jina-ai/jina pull request #3422
Opened 2021-09-16 08:35 UTC by gaocegege

It is not recommended to hard code service FQDN. 

Ref https://github.com/kubernetes/dns/blob/master/docs/specification.md

The cluster domain can be configured by the CoreDNS/KubeDNS, and it can be run without the FQDN.

2021-09-16 10:33 UTC, jacobowitz requested changes
Thank you for the change, looks good to me!

I think you just have to adapt some more tests for CI to pass

`===End Flaky Test Report===
=========================== short test summary info ============================
FAILED tests/unit/peapods/pods/test_k8s_pod.py::test_deployments[gateway-1-expected_deployments0]
FAILED tests/unit/peapods/pods/test_k8s_pod.py::test_deployments[test-pod-1-expected_deployments1]
FAILED tests/unit/peapods/pods/test_k8s_pod.py::test_deployments[test-pod-2-expected_deployments2]
FAILED tests/unit/peapods/pods/k8slib/test_kubernetes_deployment.py::test_deploy_service[None-None]
FAILED tests/unit/peapods/pods/k8slib/test_kubernetes_deployment.py::test_deploy_service[init_container1-None]
FAILED tests/unit/peapods/pods/k8slib/test_kubernetes_deployment.py::test_deploy_service[None-/test]
====== 6 failed, 206 passed, 10 skipped, 3 warnings in 217.04s (0:03:37) =======
Error: Process completed with exit code 1.`

https://github.com/jina-ai/jina/pull/3422/checks?check_run_id=3619423946

2021-09-16 10:52 UTC, gaocegege commented
Sure, will fix them ASAP. Thanks for your review.

2021-09-16 11:17 UTC, florian-hoenicke commented
@gaocegege Thanks, I did not know that we can just skip the last part of the domain name.
Will this always work when deploying it to a cluster?

2021-09-17 02:25 UTC, gaocegege commented
> @gaocegege Thanks, I did not know that we can just skip the last part of the domain name.
> Will this always work when deploying it to a cluster?

If we do not run it using hostNetwork in the deployment, it should always work. The name resolution will be handled by coreDNS.

2021-09-17 02:26 UTC, gaocegege commented
Do we have the integration test with Kubernetes?

2021-09-17 08:31 UTC, jacobowitz approved these changes
Thx for the PR :+1: 
I think its good to go. There are also K8s intergration tests in tests/k8s
They are still working so our use cases should be fine with this change.

2021-09-17 08:31 UTC, merged