docs(daemon): refactor remote executors
jina-ai/jina pull request #3432
Opened 2021-09-17 10:06 UTC by deepankarm

2021-09-17 10:21 UTC, alexcg1 requested changes
Looking good! Just a few tiny changes

2021-09-17 10:21 UTC, alexcg1 commented on docs/advanced/daemon/remote-executors.md
> +### Executor defined in yaml
- YAML

2021-09-17 10:21 UTC, alexcg1 commented on docs/fundamentals/flow/add-exec-to-flow.md
> -### Add & spawn a remote Executor via `jinad`
- & -> and

2021-09-17 10:21 UTC, alexcg1 commented on docs/fundamentals/flow/add-exec-to-flow.md
> -keyword `gpu-exec`, is put to a remote machine for parallelization, whereas other Executors stay local. Extra file
- stay**s** local
- put ~to~ **on**

2021-09-17 10:43 UTC, deepankarm commented on docs/fundamentals/flow/add-exec-to-flow.md
> -### Add & spawn a remote Executor via `jinad`
This section is removed now.

2021-09-17 10:43 UTC, deepankarm commented on docs/fundamentals/flow/add-exec-to-flow.md
> -keyword `gpu-exec`, is put to a remote machine for parallelization, whereas other Executors stay local. Extra file
same

2021-09-18 06:14 UTC, hanxiao approved these changes

2021-09-18 06:14 UTC, merged