feat: sort and return top_k Document from DocumentArray
jina-ai/jina pull request #3468
Opened 2021-09-23 22:56 UTC by sauravgarg540

This PR resolves #3467

## Resolution:
- Sort and return top_k `Document` from `DocumentArray`
- added unit test

2021-09-24 06:24 UTC, JoanFM requested changes

2021-09-24 06:24 UTC, JoanFM commented on jina/types/arrays/document.py
> +        if isinstance(self._pb_body, list):
Maybe it was not clear from the documentation. The point is to only sort the `first top_k` but of the sorted list.

There are sorting algorithms that do not sort a complete collection but that only guarantee that they first `top_k` elements are sorted while the rest may not be

2021-09-24 15:50 UTC, hanxiao commented
i dont think this implementation is needed , how is it different from `.sort()[:k]`

closing

2021-09-24 15:50 UTC, closed without merging

2021-09-24 21:36 UTC, JoanFM commented
> i dont think this implementation is needed , how is it different from `.sort()[:k]`
> 
> closing

agree, this implementation is not the proper one. This is why there are changes requested

2021-09-25 08:55 UTC, sauravgarg540 commented
Hey @JoanFM, thank you for the clarification on the issue description. I was already in doubt that why only sort first K values in a collection. I will create another PR with the correct implementation.