docs: draft image search via text
jina-ai/jina pull request #3832
Opened 2021-10-29 16:35 UTC by azayz

closes #3794

2021-10-29 18:11 UTC, JoanFM commented on docs/datatype/image/text2image.md
> +To do so, we need to figure out away to match images and texts. One way to find such matches we need to find related images with similar semantics to the query texts. This requires us to represent bo
```suggestion
To do so, we need to figure out away to match images and texts. One way to find such matches we need to find related images with similar semantics to the query texts. This requires us to represent both images and query texts in the same embedding space to be able to do the matching. In this case, pre-trained cross-modal models can help us out.
```

2021-11-10 09:44 UTC, CatStark commented on docs/datatype/image/text2image.md
> +If we had to build this from scratch, it would take a long time to build these flows. Luckily we can leverage JinaAI's tools such as Executors, Documents and Flows
Jina's tools, not JinaAI

2021-11-10 09:48 UTC, CatStark requested changes
There are still some typos. Could you check it with a spell-checker?

2021-11-10 09:48 UTC, CatStark commented on docs/datatype/image/text2image.md
> +To implement SimpleIndexer, we can leverage jina's `DocumentArrayMemmap`. You can read about this data type
Always capitalize Jina please

2021-11-10 09:48 UTC, CatStark commented on docs/datatype/image/text2image.md
> +In jina, searching for query documents can be done by adding the results to the `matches` attribute of each query
Capital letter

2021-11-10 09:48 UTC, CatStark commented on docs/datatype/image/text2image.md
> +You should find 2 folders after unzipping:
```suggestion
You should find two folders after unzipping:
```

2021-11-10 09:48 UTC, CatStark commented on docs/datatype/image/text2image.md
> +* support both **GPU** and **CPU**: That's why we will provision the `device` parameter and use it when encoding.
```suggestion
* Support both **GPU** and **CPU**: That's why we will provision the `device` parameter and use it when encoding.
```

2021-11-10 09:48 UTC, CatStark commented on docs/datatype/image/text2image.md
> +* be able to process documents in batches in order to use our resources effectively: To do so, we will use the
```suggestion
* Be able to process documents in batches in order to use our resources effectively: To do so, we will use the 
```

2021-11-10 09:48 UTC, CatStark commented on docs/datatype/image/text2image.md
> +This helper function will convert image files into Jina Documents, creates a generator and yields documents:
```suggestion
This helper function will convert the image files into Jina Documents, create a generator and yields documents:
```

2021-11-10 09:48 UTC, makram93 commented on docs/datatype/image/text2image.md
> +In this tutorial, we will create an image search system that retrieves images based on short text descriptions of their content.
```suggestion
In this tutorial, we will create an image search system that retrieves images using short text descriptions as query.
```

2021-11-10 10:11 UTC, alexcg1 requested changes
Pay special attention to capitalization, punctuation. Many other small changes

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +The interest behind this is that regular search or queries rely on image description or meta data to describe the content of the image, this is simply not efficient
- meta data -> metadata
- of the image, this is simply... -> of the image. This can be expensive and is not efficient...

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +We need to look for another solution ! What if we directly compare text with images ?
Remove space before `!`

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +To do so, we need to figure out a way to match images and texts. One way to find such matches we need to find related images with similar semantics to the query texts. This requires us to represent b
- match images and text (no s)
- One way to find such matches we need to find... -> One way to find such matches is finding...
- "texts" -> "text" (all occurrences in the doc)

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +For example when we write the word "dog" in query we want to be able to retrieve pictures with a dog in then solely by using the embeddings similarity.
- then -> them

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +Now that we understand the problem and we have an idea on how to fix it, let's try to imagine what the solution would look like :
Punctuation - remove all spaces before punctuation (i.e. `look like:` not `look like :`) - throughout this doc

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +1. We have a bunch of images with no text description about the content or anything.
- Remove "or anything"

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +This is what we call the index flow.
**Automated message**

## Capitalization

Please capitalize first letters of the following (when used to reference project or component):

- Flow
- Executor
- Document
- Jina
- Jina Hub
- Python
- Docker
- Kubernetes

### Note!

This only applies **outside** a code or CLI context. If you're describing Python, YAML, any programming language, or command line input/output, please use the capitalization you would use **in that context**.

##### Right

```python
from jina.flow import Flow
```

##### Wrong

```python
from Jina.Flow import Flow
```

---

Made with [GitHub saved replies](https://github.com/settings/replies)

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +1. We embbed the query text into the same embedding space as the image.
- embbed -> embed (please check all spelling in the doc)

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +and build such system easily.
- such a system

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +Before we begin building our pipeline we need to do a few things.
- pipeline -> Flow

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +* download [the dataset](https://open-images.s3.eu-central-1.amazonaws.com/data.zip) and unzip it.
- download -> Download

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +In this section, we will start developing the necessary executors, for both query and index flows.
capitalization

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +The CLIP model is trained to learn visual concepts from natural languages. This is done using text snippets and image pairs across the internet. In the original CLIP paper, the model performs Zero Sh
- separated -> separate
- remove space before final `.`

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +* be able to process documents in batches in order to use our resources effectively: To do so, we will use the
Capitalize first letter of bullet points

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +This helper function will convert image files into Jina Documents, creates a generator and yields documents:
- Jina Documents -> Documents

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +Now, let's build the search Flow and use it in order to find sample query images.
- Remove "in order"

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +We create a helper function to be able to plot our images
- Remove "be able to"

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +and one last function to show us the TOP 3 matches to our text query
TOP 3 -> top three

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +Now we put some texts queries which we transform into Documents and here's the results:
- here's -> here are

2021-11-10 10:11 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +Congratulations you have built a text2image search engine, you can check the full source code [here](https://colab.research.google.com/drive/1CkT1udBrMfefYo0XJO45kIpW43odLLDm?usp=sharing) and experim
- Congratulations! You have built a text-to-image search engine. You can check the full ...

2021-11-10 11:58 UTC, makram93 requested changes

2021-11-11 08:35 UTC, makram93 submitted a review, later dismissed

2021-11-11 09:43 UTC, alexcg1 requested changes
Nice job! I caught a few more things this time round, but after these changes I think we're good to go!

2021-11-11 09:43 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +The full source code of this tutorial is available in this [google colab notebook](https://colab.research.google.com/drive/1_dsJA3rxdo4g68jmqJBUeUIVH6kAXQ05?usp=sharing)
- Google Colab
- Can we host the notebook on GitHub, then import into Colab and share that? (That's what I did for https://colab.research.google.com/github/jina-ai/workshops/blob/main/memes/meme_search.ipynb) - makes it easier for others to fork

2021-11-11 09:43 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +We want an Executor that loads the CLIP model and encodes it during the index Flow.
Be clear on what "it" is

2021-11-11 09:43 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +We want an Executor that loads the CLIP model and encodes it during the query Flow.
Be clear on what "it" is

2021-11-11 09:43 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +```
Can we format this so it has linebreaks? Right now it scrolls off the side of the screen

2021-11-11 09:43 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +```
Should this be indented??

2021-11-11 09:43 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +Now, let's build the search Flow and use it to find sample query images.
- use it to search with sample query images

2021-11-11 09:43 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +```
Line breaks

2021-11-11 09:43 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +We create a helper function to plot our images
Add `:` to end of sentence

2021-11-11 09:43 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +and one last function to show us the top three matches to our text query
Add `:` to end of sentence

2021-11-11 09:43 UTC, alexcg1 commented on docs/datatype/image/text2image.md
> +Now we put some text queries which we transform into Documents and here are the results:
- put -> input

2021-11-11 22:55 UTC, hanxiao requested changes
not visible, make sure you add it to TOC

2021-11-12 10:33 UTC, alexcg1 approved these changes
LGTM :+1:

2021-11-12 12:54 UTC, makram93 approved these changes
LGTM!

2021-11-13 19:06 UTC, hanxiao requested changes
never mind, i found it

2021-11-13 19:07 UTC, merged