fix(client): assure error not called on done
jina-ai/jina pull request #3934
Opened 2021-11-15 17:08 UTC by bwanglzu

2021-11-15 17:13 UTC, JoanFM reviewed
A test needs to be added where no `on_error` is passed to see that `on_done` is not called in that case

2021-11-15 17:13 UTC, JoanFM commented on tests/unit/clients/test_helper.py
> +def flow():
flow_with_exception_request

2021-11-15 17:14 UTC, JoanFM requested changes
Some small required changes

2021-11-15 17:23 UTC, deepankarm requested changes

2021-11-15 17:23 UTC, deepankarm commented on jina/clients/helper.py
> +    elif on_done and response.status.code < jina_pb2.StatusProto.ERROR:
```suggestion
    elif on_done and response.status.code == jina_pb2.StatusProto.SUCCESS:
```

2021-11-15 17:37 UTC, JoanFM requested changes

2021-11-15 17:37 UTC, JoanFM commented on tests/unit/clients/test_helper.py
> +        on_done_mock.assert_not_called()
do these asserts outside the context, otherwise if exception test may pass

2021-11-15 20:08 UTC, JoanFM approved these changes

2021-11-16 10:41 UTC, deepankarm approved these changes

2021-11-16 10:42 UTC, merged