test: optimize k8s test
jina-ai/jina pull request #3936
Opened 2021-11-15 20:48 UTC by bwanglzu

the idea is, for every test, we always load all images. In this PR, we only load **necessary** container image w.r.t the test case.

2021-11-18 12:12 UTC, JoanFM requested changes

2021-11-18 15:13 UTC, bwanglzu commented
do not merge until we have fixed grpc issue.

2021-11-18 16:01 UTC, jacobowitz reviewed
very nice PR! I have no clue why the connection pool test is acting up, maybe we can disable it if its not easy to fix? We are reworking this atm anyway on the star routing branch.

2021-11-18 16:15 UTC, bwanglzu commented on tests/k8s/test_graceful_request_handling.py
> +    images = [
yes we can, i also want to do it (now I have more time)

2021-11-22 15:02 UTC, jacobowitz commented
I've incorporated this PR into star routing here https://github.com/jina-ai/jina/pull/3964
I think its a great speed up!
Will close this PR in favor of the other one

2021-11-22 15:02 UTC, closed without merging