perf: small improve on uuid generation in docs
jina-ai/jina pull request #3956
Opened 2021-11-18 15:07 UTC by bwanglzu

test settings: 1 million documents generation.

feature branch: 21239777 function calls (21233402 primitive calls) in 16.524 seconds

master branch: 23239839 function calls (23233463 primitive calls) in 19.815 seconds

we saved 2million function calls and roughly 17% time saving.

2021-11-18 15:24 UTC, davidbp commented
Just note that the output will be formatted  differently. From `'707a71ee-4883-11ec-a415-787b8ab3f5de'` to '707a71ee488311eca415787b8ab3f5de'. To me it still makes sense.

2021-11-18 15:59 UTC, JoanFM requested changes

2021-11-18 15:59 UTC, JoanFM commented on jina/types/document/__init__.py
> -            self.id = random_identity(use_uuid1=True)
please remove this function from the `codebase` if it nos used

2021-11-18 16:08 UTC, bwanglzu commented
we `str` conversion, it is:
```
21239914 function calls (21233528 primitive calls) in 17.544 seconds
```

2021-11-18 16:12 UTC, tadejsv commented
Can you also test by using `uuid4`? This is actually the one used now

2021-11-18 16:21 UTC, hanxiao commented
nice catch!

but then i would suggest refactoring `random_identity` to use `.hex`, instead of making this exception for Document constructor.

2021-11-18 16:23 UTC, JoanFM commented
> nice catch!
> 
> but then i would suggest refactoring `random_identity` to use `.hex`, instead of making this exception for Document constructor.

I would do that, but at the same time keep the `.hex` here, saving the function call and the `if else` can be good

2021-11-18 16:42 UTC, bwanglzu commented
okay now I break a lot of distributed test

2021-11-18 16:51 UTC, JoanFM commented
> okay now I break a lot of distributed test

no pain, no gain

2021-11-18 16:56 UTC, bwanglzu commented
> > okay now I break a lot of distributed test
> 
> no pain, no gain

:sob:

2021-11-19 12:07 UTC, JoanFM approved these changes

2021-11-19 12:08 UTC, merged