Support ssl grpc
jina-ai/jina pull request #4092
Opened 2021-12-23 07:21 UTC by mapleeit

Replacement #4091

2021-12-23 07:24 UTC, JoanFM requested changes
This will require changes in parser and proper tests

2021-12-23 07:24 UTC, JoanFM commented on jina/peapods/networking.py
> +        if options == None:
```suggestion
        if options is None:
```

2021-12-23 07:24 UTC, JoanFM commented on jina/peapods/networking.py
> +        timeout=1.0,
```suggestion
        timeout: float=1.0,
```

2021-12-23 07:24 UTC, JoanFM commented on jina/peapods/networking.py
> +        https=False,
```suggestion
        https: bool =False,
```

2021-12-23 09:06 UTC, jacobowitz requested changes
I would add tests, but I think otherwise it looks good.

This test only adds https support for the client side (the runtimes will continue to expose only insecure channels). But I think for the use case here that is good enough because TLS termination happens before. So for me this approach here is valid!

2021-12-23 09:39 UTC, mapleeit commented
Ok. I'll add the tests then.

2021-12-24 09:06 UTC, mapleeit commented
I added test for static connection pool methods. 

But it's not easy to add test for Client since we don't have a https Flow. I can keep it as it is originally if you want. @jacobowitz @JoanFM

2021-12-25 03:16 UTC, urica12 commented
Great

2021-12-26 11:07 UTC, jacobowitz requested changes
Commit message linting failed, you need to rewrite some of your messages according to the commit style guide. Otherwise I only have one minor coding style suggestion, the rest looks good to me. Nice feature :+1:

2021-12-26 11:07 UTC, jacobowitz commented on jina/peapods/networking.py
> +            if root_certificates is not None:
I think its okay to pass None as root_certificates to ssl_channel_credentials(), see https://grpc.github.io/grpc/python/_modules/grpc.html#ssl_channel_credentials

so I would simplify line 485 to 488 to the single line
credentials = grpc.ssl_channel_credentials(
                    root_certificates=root_certificates
                )
no first call without args and no if needed?

2021-12-30 05:58 UTC, mapleeit commented
Comments addressed. @jacobowitz

2021-12-30 08:45 UTC, jacobowitz requested changes
commit linting is failing (I think commit messages should not be capitalized after the colon, so no feat: Update ...).

Otherwise the PR looks good to me!

2021-12-30 08:59 UTC, mapleeit commented
Commit lint fixed

2021-12-30 14:05 UTC, jacobowitz approved these changes
neat addition :+1:

2021-12-30 14:05 UTC, merged