Docs3 0 migration guide
jina-ai/jina pull request #4263
Opened 2022-02-09 09:00 UTC by JohannesMessner

Moved PR due to renamed branch

2022-02-09 09:34 UTC, alexcg1 requested changes

2022-02-09 09:34 UTC, alexcg1 commented on docs/migrate-to-jina3/migrate.md
> +Accordingly, the scope of the changes in Jina 3 will be mainly related to `Document` and `DocumentArray`.
Need a new line here

2022-02-09 09:34 UTC, alexcg1 commented on docs/migrate-to-jina3/migrate.md
> +Accordingly, the scope of the changes in Jina 3 will be mainly related to `Document` and `DocumentArray`.
Before `Accordingly`

2022-02-09 09:34 UTC, alexcg1 commented on docs/migrate-to-jina3/migrate.md
> +## Simplified access of attributes and elements
```suggestion
## Simplified access to attributes and elements
```

2022-02-09 15:47 UTC, JohannesMessner commented
Not ready to merge yet, currently incorporating feedback from the doc coaching

2022-02-10 08:31 UTC, JoanFM requested changes

2022-02-10 08:31 UTC, JoanFM commented on docs/migrate-to-jina3/migrate.md
> +  Additionally, you can access a specific key in `tags` by calling `docs[:'tags__key']`.
```suggestion
  Additionally, you can access a specific key in `tags` by calling `docs[:, 'tags__key']`.
```

2022-02-10 08:31 UTC, JoanFM commented on docs/migrate-to-jina3/migrate.md
> +## Pythonic serialization
Try to group the changes between `Document`, `DocumentArray` based changes and the `Flow` ones.

2022-02-10 08:57 UTC, JoanFM requested changes
Also mention that `DocumentArrayMemmap` is removed

2022-02-10 16:55 UTC, JoanFM approved these changes

2022-02-10 16:56 UTC, merged