docs: add scale tutorial
jina-ai/jina pull request #4268
Opened 2022-02-09 16:33 UTC by bwanglzu

2022-02-10 14:50 UTC, JoanFM requested changes

2022-02-10 14:50 UTC, JoanFM commented on docs/tutorials/scale-out.md
> +The Executor looks like this:
```suggestion
The Executor may look like this:
```

2022-02-10 14:50 UTC, JoanFM commented on docs/tutorials/scale-out.md
> +And we create a `Flow` and make use some text corpus from sklearn to use this `Executor`:
```suggestion
Then we create a `Flow` and make use some text corpus from sklearn to use this `Executor`:
```

2022-02-10 14:50 UTC, JoanFM commented on docs/tutorials/scale-out.md
> +Instead of scale an `Executor` at creation time,
For now let's remove this part, we are not sure we want to promote this feature.

We prefer to have users with these concerns go to `Kubernetes` at the moment

2022-02-10 14:50 UTC, JoanFM commented on docs/tutorials/scale-out.md
> +* Please install several dependencies , includes jina and sklearn.
```suggestion
* Please install several dependencies , including jina and sklearn.
```

2022-02-10 17:24 UTC, JoanFM requested changes

2022-02-10 17:24 UTC, JoanFM commented on docs/tutorials/scale-out.md
> +If you want to distribute your data to different places, Jina allows you to use `shards` to specify number of shards.
Mention that `Jina` will automaticall `reduce` the `results` to collect `matches` from `different` shards`

2022-02-10 17:29 UTC, bwanglzu commented on docs/tutorials/scale-out.md
> +* Please install several dependencies , includes jina and sklearn.
will fix the gramma since once finished

2022-02-11 15:06 UTC, JoanFM approved these changes

2022-02-11 16:02 UTC, closed without merging