feat(executor): add serve function
jina-ai/jina pull request #4475
Opened 2022-03-14 11:54 UTC by hanxiao

on developing remote Executor, I have to quickly make an Executor "served", I hope there is a shortcut for doing the following work:

```python
from jina import Flow

f = Flow(port=12345).add(uses=MyExec)
with f:
    f.block()
```

so now I can:

```python
from jina import Executor

class MyExec(Executor):
  ...

MyExec().serve()
```

Please improve doc or whatever needs. I wont have time to revisit this PR, hope to see it merge soon.

2022-03-14 12:04 UTC, JoanFM requested changes

2022-03-14 12:04 UTC, JoanFM commented on jina/serve/executors/__init__.py
> +        self,
I would not have this as a method of the instance, but a `class` method

2022-03-14 12:04 UTC, JoanFM commented on jina/serve/executors/__init__.py
> +            uses=type(self),
therefore u could pass `cls`

2022-03-14 16:43 UTC, JoanFM requested changes
Please add at least small test about the feature

2022-03-14 16:43 UTC, JoanFM commented on docs/fundamentals/executor/executor-api.md
> +## Serve Executor without Flow
I would call it `serve Executor standalone`

2022-03-15 08:28 UTC, JoanFM approved these changes

2022-03-15 12:18 UTC, JohannesMessner approved these changes

2022-03-15 12:19 UTC, merged