Refactor docs flow
jina-ai/jina pull request #4547
Opened 2022-03-25 13:44 UTC by samsja

https://github.com/jina-ai/jina/issues/4545

2022-03-28 07:03 UTC, JoanFM requested changes

2022-03-28 07:03 UTC, JoanFM commented on docs/fundamentals/flow/flow-api.md
> +There are two ways of defining a FLow, either directly from the Python API or using yaml files. For each section we will show you both possibles way of configuring your flow.
```suggestion
There are two ways of defining a Flow, either directly from the Python API or using yaml files. For each section we will show you both possibles way of configuring your flow.
```

2022-03-28 07:03 UTC, JoanFM commented on docs/fundamentals/flow/flow-api.md
> +To configure it yaml just do
```suggestion
To configure it using yaml just do
```

2022-03-29 11:26 UTC, JohannesMessner requested changes

2022-03-29 11:26 UTC, JohannesMessner commented on docs/fundamentals/flow/flow-api.md
>  Every `Flow` provides an API to receive requests over the network. Supported protocols are gRPC, HTTP and websockets.
```suggestion
Every `Flow` provides an API to receive requests over the network. Supported protocols are gRPC, HTTP and WebSocket.
```

2022-03-29 11:26 UTC, JohannesMessner commented on docs/fundamentals/flow/flow-api.md
> +## Serve Flow With Different Protocol
```suggestion
## Serve Flow with different protocols
```

2022-03-29 11:26 UTC, JohannesMessner commented on docs/fundamentals/flow/flow-api.md
> +To configure it using yaml just do
```suggestion
To configure the protocol using a YAML file, just do
```

2022-03-29 11:26 UTC, JohannesMessner commented on docs/fundamentals/flow/flow-api.md
> +Note that grpc is the default protocol so you can just ommit it
```suggestion
Note that gRPC is the default protocol, so you can just omit it.
```

2022-03-29 11:26 UTC, JohannesMessner commented on docs/fundamentals/flow/flow-api.md
>  You can add more kwargs to build richer semantics on your HTTP endpoint. Those meta information will be rendered by Swagger UI and be forwarded to the OpenAPI schema.
```suggestion
You can add more `kwargs` to build richer semantics on your HTTP endpoint. Those meta information will be rendered by Swagger UI and be forwarded to the OpenAPI schema.
```

2022-03-30 12:42 UTC, JoanFM approved these changes

2022-03-30 12:45 UTC, JohannesMessner approved these changes

2022-03-30 12:51 UTC, merged