docs: refactor access flow page
jina-ai/jina pull request #4573
Opened 2022-04-01 13:27 UTC by cristianmtr

# refactor the "access flow" page

To follow the structure in https://github.com/jina-ai/internal-tasks/issues/401

2022-04-01 14:02 UTC, JohannesMessner requested changes
In the websocket section there is a slightly passive aggressive (imho) bullet point about not using gRPC if the user is lazy. Maybe instead of this we can have a very short section about gRPC (on the same level with http, graphql, websocket) that says that in principle you could use it from any langauge by compiling jina.proto, but that we only actively support our python client for this or something like that?

2022-04-04 06:57 UTC, samsja reviewed
the graphql endpoint is wrongly formatted in that part of the docs. You could maybe fix it with that PR
![Screenshot from 2022-04-04 08-55-22](https://user-images.githubusercontent.com/55492238/161489523-f8d6d02f-5961-4240-9a01-f4d13e462ede.png)

2022-04-04 06:57 UTC, samsja commented on docs/fundamentals/flow/access-flow-api.md
> +Apart from using the {ref}`Jina Client <client>`, the most common way of interacting way with your deployed Flow is via HTTP.
```suggestion
Apart from using the {ref}`Jina Client <client>`, the most common way of interacting with your deployed Flow is via HTTP.
```

2022-04-06 12:25 UTC, cristianmtr commented on docs/fundamentals/flow/access-flow-api.md
> +| `execEndpoint`   | **required** | Executor {ref}`endpoint <executor-requests>` to target                                 | `"execEndpoint": "/index"`                        |
Which link? I think this was an older version

2022-04-06 12:26 UTC, cristianmtr commented on docs/fundamentals/flow/access-flow-api.md
> +This page is about accessing the Flow with external clients. You can also use the Jina Client, provided by us in the `jina` package.
added

2022-04-06 12:28 UTC, cristianmtr commented on docs/fundamentals/flow/access-flow-api.md
> +Apart from using the {ref}`Jina Client <client>`, the most common way of interacting way with your deployed Flow is via HTTP.
done

2022-04-06 12:29 UTC, cristianmtr commented
> the graphql endpoint is wrongly formatted in that part of the docs. You could maybe fix it with that PR ![Screenshot from 2022-04-04 08-55-22](https://user-images.githubusercontent.com/55492238/161489523-f8d6d02f-5961-4240-9a01-f4d13e462ede.png)

Which part?

2022-04-07 09:32 UTC, samsja commented
> > the graphql endpoint is wrongly formatted in that part of the docs. You could maybe fix it with that PR ![Screenshot from 2022-04-04 08-55-22](https://user-images.githubusercontent.com/55492238/161489523-f8d6d02f-5961-4240-9a01-f4d13e462ede.png)
> 
> Which part?

the gateway which is in purple is wrongly formatted ( the purple come from my mouse when I did the screenshot)

2022-04-07 10:08 UTC, cristianmtr commented
> > > the graphql endpoint is wrongly formatted in that part of the docs. You could maybe fix it with that PR ![Screenshot from 2022-04-04 08-55-22](https://user-images.githubusercontent.com/55492238/161489523-f8d6d02f-5961-4240-9a01-f4d13e462ede.png)
> > 
> > 
> > Which part?
> 
> the gateway which is in purple is wrongly formatted ( the purple come from my mouse when I did the screenshot)

So you wanted it to be between backticks, right? Like so 

![image](https://user-images.githubusercontent.com/8330330/162175902-e497c765-06e7-4736-826b-0047fec2e923.png)

2022-04-07 11:43 UTC, samsja approved these changes

2022-04-08 07:48 UTC, JohannesMessner approved these changes

2022-04-08 07:52 UTC, merged