docs: restructure flow yaml instructions
jina-ai/jina pull request #4574
Opened 2022-04-01 13:37 UTC by JohannesMessner

2022-04-04 07:07 UTC, samsja requested changes

2022-04-04 07:07 UTC, samsja commented on docs/fundamentals/flow/create-flow.md
>  ````{tab} Pythonic style
Do we keep Pythonic style ? Or just say Python ?

2022-04-04 07:07 UTC, samsja commented on docs/fundamentals/flow/create-flow.md
> +For professional use we recommend YAML files to configure your Flows.
```suggestion
For production use we recommend YAML files to configure your Flows.
```

2022-04-06 11:50 UTC, cristianmtr requested changes
The line 

```
Jina `Flow`s are context managers and can be started and stopped using Pythons with notation:
```

should be changed to

```
Jina Flows are context managers and can be started and stopped using Pythons with notation:
```

No backticks when we refer to the items as objects, and not as code directly

This line too

```
Executors from code, being defined outside your current `PATH` environment variable
```

to

```
You can use Executors from module outside your `PATH` environment variable
```

This

```
configuration in a separate configuration yaml,  which will be used in the `Flow`:
```

to

```
configuration in a separate configuration YAML,  which will be used in the Flow:
```

2022-04-06 11:50 UTC, cristianmtr commented on docs/fundamentals/flow/create-flow.md
> +It defines how your Executors are tied together, and how your data, well, *flows*.
```suggestion
It defines how your Executors are connected together and how your data *flows* through them.
```

The pun is cute, but might be distracting

2022-04-06 11:50 UTC, cristianmtr commented on docs/fundamentals/flow/create-flow.md
> +- human-readable
Probably meant that you don't need to understand the Python code surrounding the definition, but just read the YAML object definitions as their own things.

2022-04-06 11:50 UTC, cristianmtr commented on docs/fundamentals/flow/create-flow.md
>  ````{tab} Pythonic style
```suggestion
````{tab} Python
```

2022-04-06 11:50 UTC, cristianmtr commented on docs/fundamentals/flow/create-flow.md
> +`````{tab} Load from YAML
```suggestion
`````{tab} YAML
```

2022-04-06 11:50 UTC, cristianmtr commented on docs/fundamentals/flow/create-flow.md
> +In addition to loading a Flow from a YAML file, you can also dump an existing Flow to YAML. To do so, execute `f.save_config('path/to/flow.yml')`.
```suggestion
In addition to loading a Flow from a YAML file, you can also save an existing Flow configuration to YAML. To do so, execute `f.save_config('path/to/flow.yml')`.
```

I'd say the word "dump" should be avoided a bit, if we can

2022-04-14 12:23 UTC, JoanFM approved these changes

2022-04-14 15:15 UTC, samsja approved these changes

2022-04-19 07:33 UTC, JoanFM approved these changes

2022-04-19 08:29 UTC, JoanFM approved these changes

2022-04-19 08:34 UTC, cristianmtr approved these changes

2022-04-19 08:35 UTC, merged