fix: parsing requirements of executor
jina-ai/jina pull request #4698
Opened 2022-04-26 15:20 UTC by numb3r3

Goals:
To allow the following URI or VCS requirements can be parsed correctly:
```
git+https://github.com/huggingface/transformers.git
git+https://github.com/patil-suraj/vqgan-jax.git
git+https://github.com/borisdayma/dalle-mini.git
```

2022-04-26 16:26 UTC, JoanFM requested changes

2022-04-26 16:26 UTC, JoanFM commented on tests/unit/hubble/test_helper.py
> +def test_parse_requirements():
I think a better test should be built.

2022-04-26 16:54 UTC, numb3r3 commented on tests/unit/hubble/test_helper.py
> +def test_parse_requirements():
a stronger test is added.

2022-04-27 09:05 UTC, JoanFM approved these changes

2022-04-27 09:06 UTC, merged