Fix rich console logs
jina-ai/jina pull request #4724
Opened 2022-04-29 12:45 UTC by samsja

Fixing : https://github.com/jina-ai/jina/issues/4612

2022-04-29 13:06 UTC, JoanFM commented
Please paste a before & after comparison

2022-04-29 13:46 UTC, JoanFM requested changes

2022-04-29 13:49 UTC, samsja commented
Before : 
in CI
![Screenshot from 2022-04-29 15-45-07](https://user-images.githubusercontent.com/55492238/165956995-154be19e-8c6c-407e-890f-c67d78185343.png) ( see here https://github.com/jina-ai/jina/runs/6228360791?check_suite_focus=true)

working in pycharm :heavy_check_mark: 

After:

in CI:
![Screenshot from 2022-04-29 15-45-34](https://user-images.githubusercontent.com/55492238/165957005-8b72074a-f8a8-4ce2-a7c7-60a93b710bf7.png)
(see here https://github.com/jina-ai/jina/runs/6229123758?check_suite_focus=true)

 working in pycharm :heavy_check_mark:

2022-04-29 18:12 UTC, hanxiao commented on jina/helper.py
> +        force_terminal=True if os.getenv('PYCHARM_HOSTED') else None,
```suggestion
        force_terminal=True if 'PYCHARM_HOSTED' in os.environ else None,
```

2022-05-02 09:08 UTC, JoanFM approved these changes

2022-05-02 09:08 UTC, merged