feat: add a decoratator for monitoring method
jina-ai/jina pull request #4737
Opened 2022-05-02 12:40 UTC by samsja

Follow up of https://github.com/jina-ai/clip-as-service/pull/674

Goal:

Having an decorator to monitor internal method of an Executor

2022-05-03 12:49 UTC, JoanFM requested changes

2022-05-03 12:49 UTC, JoanFM commented on jina/serve/executors/__init__.py
> +    from jina import DocumentArray
```suggestion
    from docarray import DocumentArray
```

2022-05-04 13:48 UTC, JoanFM requested changes

2022-05-04 13:48 UTC, JoanFM commented on jina/serve/executors/__init__.py
> +    from jina import DocumentArray
```suggestion
    from docarray import DocumentArray
```

2022-05-04 13:48 UTC, JoanFM commented on jina/serve/executors/decorators.py
> +            else:  # should raise a warning or log something about the fact the monitoring is disabled
what about this comment, why is not implemented?

2022-05-05 07:48 UTC, hanxiao commented
```
@monitor('metrics_name', 'metrics description')
```

1. what are the available matric names?
2. it is better to force the explicit kwargs, with `*`: https://stackoverflow.com/a/14298976
3. if metrics_name is basically an enum, then why the description is required, isn't the description best described by us?

2022-05-05 11:37 UTC, samsja commented
> 

'metric_name' is the name that will appear on prometheus. For example if you are monitoring the time that clip as a service spend processing some text you will call it `text_preprocessing`. **It is not an enum for the type of the metric**, therefore the description is used to give more context on what the function which is wrapped by monitoring is doing.
Btw the user can as well just call `@monitor` and it will produce a name and a description automatically based on the name of the function ( everything will be documented in the documentation pr)

2022-05-05 11:40 UTC, samsja commented
> ```
> @monitor('metrics_name', 'metrics description')
> ```
> 
>     1. what are the available matric names?
> 
>     2. it is better to force the explicit kwargs, with `*`: https://stackoverflow.com/a/14298976
> 
>     3. if metrics_name is basically an enum, then why the description is required, isn't the description best described by us?

for point 2. you are right I will update it

2022-05-05 17:40 UTC, JoanFM requested changes
I am missing unit tests for the monitor decorator

2022-05-09 07:52 UTC, JoanFM approved these changes

2022-05-09 07:53 UTC, merged