Gateway endpoint discovery
jina-ai/jina pull request #4756
Opened 2022-05-06 07:22 UTC by JoanFM

Goals:

- ...
- ...
- [ ] check and update documentation. See [guide](https://github.com/jina-ai/jina/CONTRIBUTING.md#documentation-guidelines) and ask the team.

2022-05-06 08:32 UTC, jacobowitz requested changes

2022-05-06 08:32 UTC, jacobowitz commented on jina/proto/jina.proto
> + * jina gRPC service for DataRequests.
That comment is not correct

2022-05-06 08:32 UTC, jacobowitz commented on jina/serve/runtimes/gateway/graph/topology_graph.py
> +                    if endpoint is not None:
why nesting and not concatenating with and?

2022-05-06 08:32 UTC, jacobowitz commented on jina/serve/runtimes/head/__init__.py
> +        Process the received requests and return the result as a new request
that comment is not valid

2022-05-06 08:32 UTC, jacobowitz commented on jina/serve/runtimes/worker/__init__.py
> +        Process the received requests and return the result as a new request
comment outdated

2022-05-06 08:32 UTC, jacobowitz commented on jina/serve/networking.py
> +            Send requests and uses the appropriate grpc stub for this
comment outdated

2022-05-06 08:32 UTC, jacobowitz commented on jina/serve/networking.py
> +            return response, metadata
```
return await self.endpoints_discovery_stub.endpoint_discovery(
                jina_pb2.google_dot_protobuf_dot_empty__pb2.Empty(),
                timeout=timeout)
```

you are not really interested in the metadata no?

2022-05-06 08:32 UTC, jacobowitz commented on jina/serve/networking.py
> +        """Send a request to target via one or all of the pooled connections, depending on polling_type
comment not correct

2022-05-06 08:32 UTC, jacobowitz commented on jina/serve/networking.py
> +                    print(f' JOAN HERE ERROR {e}')
left over print

2022-05-09 11:27 UTC, samsja approved these changes
lgtm

2022-05-09 11:28 UTC, merged