feat: add additional metrics
jina-ai/jina pull request #4789
Opened 2022-05-16 12:29 UTC by samsja

linked to https://github.com/jina-ai/jina/issues/4731

- [ ] Number of fails: How many requests failed, exception type etc 
- [ ] Request size: In bytes of the request object
- [ ]  Number of Clients connected: gateway only 
- [ ] Number of pending requests: gateway only

2022-05-16 14:58 UTC, JoanFM requested changes
Some tests should be added

2022-05-18 11:04 UTC, samsja commented
> Some tests should be added

I added integration tests for both of the current metrics

2022-05-19 10:45 UTC, JoanFM requested changes

2022-05-19 10:45 UTC, JoanFM commented on tests/integration/monitoring/test_monitoring.py
> +            assert not p.exitcode
collect the exit codes and assert after all of them have been terminated, to avoid timeouts

2022-05-19 11:41 UTC, JoanFM approved these changes

2022-05-19 15:52 UTC, merged