feat: smart replica retry
jina-ai/jina pull request #4794
Opened 2022-05-17 11:36 UTC by JohannesMessner

Right now, when a replica fails (on local), the gateway will stubbornly retry to connect to that same replica, instead of trying its luck with one of the other replicas. This PR changes that, applying round robing scheduling also for retries, not just successful calls.

2022-05-19 11:42 UTC, JoanFM requested changes

2022-05-19 11:42 UTC, JoanFM commented on jina/serve/networking.py
> +            # returns all replicas of a given deployment, using a "random" shard
Not a `random` but a given one

2022-05-19 11:50 UTC, samsja commented on jina/serve/networking.py
> +                connection = connections.get_next_connection()
I find it really confusing to have `connection` for the single entity and `connections` for the group.
Maybe `current_connexion` ?

2022-05-19 14:37 UTC, JoanFM requested changes

2022-05-19 14:37 UTC, JoanFM commented on tests/integration/runtimes/test_network_failures.py
> +        assert p.exitcode == 0
assert these after u have finished every assert in the test, otherwise it may be left hanging

2022-05-20 09:50 UTC, JoanFM approved these changes

2022-05-20 09:50 UTC, merged