fix: remove tag from save config yaml
jina-ai/jina pull request #4809
Opened 2022-05-19 16:33 UTC by samsja

The output of `f.save_config()` should not include `!Flow` since it is deprecated syntax and not compatible with jcloud.

2022-05-19 16:35 UTC, samsja commented
Turns out it is not that easy ...

https://github.com/yaml/pyyaml/issues/408

2022-05-19 20:02 UTC, JoanFM requested changes
A test would be needed

2022-05-25 14:13 UTC, JoanFM reviewed
didn't we want to have a custom `Dumper`?

2022-05-25 14:37 UTC, JohannesMessner commented
> didn't we want to have a custom `Dumper`?

We did, but
1) I don't think it is necessary if we can fix the issue with 1 LOC, and
2) not sure if it would even work. Internally, pyyaml represents the yaml as a graph of `node`s, and every `node` needs to have a `tag`. This cannot be `''` or `None`. So I suspect that even with a custom Dumper we would end up with the same solution anyways. For example, dumping a normal Python `dict` internally also does the same thing (just even hackier, this magic string is the same as the tag that I use):
```python
def represent_dict(self, data):
    return self.represent_mapping('tag:yaml.org,2002:map', data)
```

2022-05-27 08:21 UTC, JoanFM approved these changes

2022-05-27 12:57 UTC, merged