refactor(docs): update docker compose docs
jina-ai/jina pull request #4820
Opened 2022-05-23 13:40 UTC by samsja

fixing https://github.com/jina-ai/jina/issues/4679

2022-05-23 13:47 UTC, JoanFM requested changes

2022-05-23 13:47 UTC, JoanFM commented on docs/how-to/docker-compose.md
> -  indexer-head:   # # # # # # # # # # #
are u sure there is no head here where there are `shards`?

2022-05-23 13:47 UTC, JoanFM commented on docs/how-to/docker-compose.md
> -- 3 associated with the indexer, one for the Head and two for the Shards.
there should be a Head for those with `shards`

2022-05-24 07:36 UTC, JoanFM approved these changes

2022-05-24 07:47 UTC, samsja commented
please wait before merging this PR. It seems like the da use for the example is not save in jina cloud

2022-05-24 08:15 UTC, merged