docs: document behaviour when things go wrong and redo k8s howto
jina-ai/jina pull request #4842
Opened 2022-05-30 14:30 UTC by JohannesMessner

**ToDO**
- [x] document error handling behaviour. See here: https://docs-failures--jina-docs.netlify.app/fundamentals/flow/when-things-go-wrong/
- [x] polish k8s HowTo. See here: https://docs-failures--jina-docs.netlify.app/how-to/kubernetes/
- [x] @samsja edit the "expose flow" details

2022-05-31 08:11 UTC, samsja commented
I am wondering if it could be useful to have a section where we explain what could have gone wrong when user see `|Gateway: Communication error with deployment...`

Could be nice to have the error message in our docs so that user will find this page when googling this error. (our with docsQA)

2022-05-31 12:22 UTC, JohannesMessner commented
@samsja please add your suggested improvements to the snippets that access the deployed Flow!

2022-06-01 07:56 UTC, JoanFM requested changes

2022-06-01 07:56 UTC, JoanFM commented on docs/how-to/kubernetes.md
> +When deployed in Kubernetes, these Executors will run inside Kubernetes Pods as containers and their lifetime will be handled
```suggestion
When deployed in Kubernetes, these Executors will run inside Kubernetes Pods as containers and their lifetime will be orchestrated
```

2022-06-01 07:56 UTC, JoanFM commented on docs/how-to/kubernetes.md
> +        uses='jinahub+docker://PQLiteIndexer',
ANNLite is the new name, so keep ANNLite

2022-06-02 12:55 UTC, JoanFM requested changes

2022-06-02 12:55 UTC, JoanFM commented on docs/how-to/kubernetes.md
> +encoder-head-55bbb477ff-p2bmk     1/1     Running   0          60m
we should rerun this to show new message without `encoder-head`

2022-06-02 12:58 UTC, JoanFM approved these changes

2022-06-02 14:37 UTC, JohannesMessner commented on docs/how-to/kubernetes.md
> +We need first to forward the Kubernetes services to your local machine by doing
```suggestion
First, you need to forward the Kubernetes services to your local machine by doing
```

2022-06-02 14:37 UTC, JohannesMessner commented on docs/how-to/kubernetes.md
> +Now we can define a client to connect to our Flow running in Kubernetes:
```suggestion
Now you can define a Client to connect to your Flow running in Kubernetes:
```

2022-06-02 14:37 UTC, JohannesMessner commented on docs/how-to/kubernetes.md
> +Then let's index the set of images we want to search:
```suggestion
Then you can index the set of images that you want to search:
```

2022-06-02 14:37 UTC, JohannesMessner commented on docs/how-to/kubernetes.md
> +Then let's search for the closest image to our query image:
```suggestion
Then, search for the closest image to our query image:
```

2022-06-02 14:43 UTC, samsja approved these changes

2022-06-02 15:20 UTC, merged