feat: error handling for executor timeouts
jina-ai/jina pull request #4899
Opened 2022-06-08 14:14 UTC by JohannesMessner

**Goal:** Handle timeouts the same way that connection errors are handled: retries are applied, and useful error messages are propagated to the user.

**ToDo:**
- [x] gRPC gateway
- [x] http gateway
- [x] ws gateay
- [x] testing
- [x] docs

2022-06-08 15:14 UTC, JoanFM requested changes

2022-06-08 15:14 UTC, JoanFM commented on jina/serve/runtimes/gateway/graph/topology_graph.py
> +                    f' You can increase the allowed time by setting `Flow(timeout_send=time_in_ms)`.'
maybe change to setting `timeout_send` attribute in your Flow, which can aplly also to a Flow with `yaml`

2022-06-09 09:12 UTC, JohannesMessner commented on tests/integration/gateway_clients/test_executor_timeout_failures.py
> +    f = Flow(timeout_send=1, protocol=protocol).add(uses=SlowExecutor, shards=2)
it is passed to the `_test_error` method in a new process and enters a context manager there. Unfortunately gRPC and pytest don't play nice together, so this has to be done in a new subprocess. I don't think entering the Flow context manager here would work.

2022-06-09 10:19 UTC, JoanFM commented on tests/integration/gateway_clients/test_executor_timeout_failures.py
> +    f = Flow(timeout_send=1, protocol=protocol).add(uses=SlowExecutor, shards=2)
please do not pass a Flow to another process, it is a bad pattern, pass perhaps the arguments but not the Flow, if it is already like this in other tests please change.

Pickling a Flow object is a little weird

2022-06-09 10:58 UTC, JohannesMessner commented on tests/integration/gateway_clients/test_executor_timeout_failures.py
> +    f = Flow(timeout_send=1, protocol=protocol).add(uses=SlowExecutor, shards=2)
Ok that makes sense, didn't think about it too much. Will change

2022-06-09 12:39 UTC, JoanFM approved these changes

2022-06-09 12:39 UTC, merged