docs: create api reference
jina-ai/jina pull request #4913
Opened 2022-06-10 12:37 UTC by JohannesMessner

Goals:

Create a proper API reference page.

The changed commit bot leads to the following behaviour:
- For any **class/method that gets its arguments from a parser, docstrings are generated automatically** (this was already the case before)
- Now, **if there are `@overload` methods, all :param: information will automatically also be added to the final stub**, the one that holds the actual implementation
- If the parser changes, this information is updated automatically. This means that **`:param:` descriptions come from the parser and should be modified there**
- the bot is smart enough to distinguish the auto-generated part of the docstring (all the `:param:`s etc.), from the hand written top level description. **This means that class/method descriptions can be edited directly in the docstring.**
- If there is a `@overload` stub that does _not_ get its arguments from a parser, then the bot can not know about them automatically. In that case, the `:param:` info has to be added in the bot script, like [here](https://github.com/jina-ai/jina/pull/4913/files#diff-386893c98d26e69d4f2e67efee373ebdf8f35dc01621373ed4d76b4ed0a25dd8R292).

Tasks:

- [x] make it so that inherited properties and methods show up
- [x] create landing page that only shows classes/functions that are actually interesting to the user (our "official" API)
  - [x] fix alignment/whitespace in a non-hacky way (ideas welcome)
- [x] make it so that `__init__()` docstrings are shown on the class level
- [x] make it so that docstrings from overloaded methods/functions are all aggregated and displayed
- [ ] write better docstrings (optional, can be its own PR)

2022-06-13 07:58 UTC, JoanFM requested changes
Please add, whatever script you used to generate this reference, and make it part of some CI/CD action to update it

2022-06-13 08:05 UTC, samsja commented
> Please add, whatever script you used to generate this reference, and make it part of some CI/CD action to update it

The beautifull part is that we did not used any additional script. Turns out sphinx allow to do that automatically. Finding the parameters to do it what an other challenge though

2022-06-13 08:06 UTC, JohannesMessner commented
> Please add, whatever script you used to generate this reference, and make it part of some CI/CD action to update it

There is no script, we hand generated the "landing page", following the example of sklearn: https://scikit-learn.org/stable/modules/classes.html
We think it makes sense this way, because it lets us actually choose what our official API is, and what should be hidden from the user; and it lets us put those important objects to the front instead of them being hidden deep in our nested package structure.

Also note that this is still highly WIP, we are having trouble to make these tables look not-horrible.

2022-06-13 11:51 UTC, JohannesMessner commented
We are currently **blocked** for the following reason:

For overloaded methods/functions (`@overload`), *only the docstring of the last signature* (the one that holds the actual implementation) *is shown* in the generated docs. The problem is that all the useful information is at the level of the overloaded stubs, since they show the arguments as the users sees them, whereas the implemenetation signature usually only holds `args` and `kwargs`.
An **[example](https://github.com/jina-ai/jina/blob/master/jina/orchestrate/flow/base.py#L105)** for this is the Flow class, where the [implementation signature](https://github.com/jina-ai/jina/blob/master/jina/orchestrate/flow/base.py#L321) has no docstring at all, but the overloaded stubs do.

As I see it, there are two ways of solving this:
1. Have sphinx automatically compile all the overloaded docstrings and display them all. I don't know if this is possible. I found [this](https://sphinx-toolbox.readthedocs.io/en/latest/extensions/more_autodoc/overloads.html) extension which might (?) do what we need it to, but it throws an exception when I try it.
2. Put the entire and complete docstring below the implementation (last) signature, for every overloaded method. Does anyone know if it would be possible to enforce this in linting, similar to how we currently already enforce docstrings for public methods?

2022-06-14 11:13 UTC, JohannesMessner commented
CI isn't passing because one commit message is too long. This is a bit of a pain to fix because it is so far back in history, but the problem should solve itself when squash & merge is performed.

2022-06-14 11:53 UTC, JoanFM commented on jina/orchestrate/flow/base.py
> -        :param uses_after: The executor attached after the Pods described by --uses, typically used for receiving from all shards, accepted type follows `--uses`. This argument only applies for shard
ans where all they go?

2022-06-14 12:19 UTC, JohannesMessner commented on jina/orchestrate/flow/base.py
> +        :param uses_after: The executor attached after the Pods described by --uses, typically used for receiving from all shards, accepted type follows `--uses`. This argument only applies for shard
@JoanFM I think here is what you are looking for. It is present both under the `@overload` stub and under the implementation stub.

2022-06-14 17:10 UTC, JohannesMessner commented
Converting back to draft because I may have found the clean solution to create a nicely aligned landing page, including having a single page for each class/function, and automatically pulling descriptions from the docstring. I'll give it a try tomorrow, let's wait with the merge until then.

2022-06-15 07:34 UTC, samsja commented
For me the next step of this PR are :

- [ ] Try to show in the search response whereas it is in the docstring on in the User guide
- [ ] remove the classes that are not in the new Python API reference from the search result

2022-06-15 14:19 UTC, JohannesMessner commented
> For me the next step of this PR are :
> 
> * [ ]  Try to show in the search response whereas it is in the docstring on in the User guide
> * [ ]  remove the classes that are not in the new Python API reference from the search result

I think search should go in a separate PR, it is its own issue, in this here can provide value without improved search, so we should merge it as soon as we can.

2022-06-16 09:16 UTC, JohannesMessner commented on jina/orchestrate/flow/base.py
>          needs = kwargs.get('needs', None)
```suggestion
        """
        ## implementation_stub_inject_end_add
        needs = kwargs.get('needs', None)
```

2022-06-16 09:16 UTC, JohannesMessner commented on jina/orchestrate/flow/base.py
```suggestion
        **kwargs) -> Union['Flow', 'AsyncFlow']:
         implementation_stub_inject_start_add
         
        """Add an Executor to the current Flow object.

```

2022-06-16 09:22 UTC, JohannesMessner commented on jina/orchestrate/flow/base.py
```suggestion
        **kwargs) -> Union['Flow', 'AsyncFlow']:
        
        # implementation_stub_inject_start_add
        """Add an Executor to the current Flow object.

```

2022-06-16 12:10 UTC, merged