chore(issue_templates) change wording
jina-ai/jina pull request #4995
Opened 2022-07-05 14:06 UTC by ArjunSharda

Changes wording of some issue templates

2022-07-05 15:36 UTC, JoanFM requested changes
Thanks for contributiing, but I think there are some changes to be applied

2022-07-05 15:36 UTC, JoanFM commented on .github/ISSUE_TEMPLATE/config.yml
> +  - name: "📚 View the docs"
```suggestion
  - name: "📚 Read the docs"
```

2022-07-05 15:36 UTC, JoanFM commented on .github/ISSUE_TEMPLATE/---can-jina-do-this-.md
> +about: Open question such as: I want to use Jina for X, but not sure if Y is doable.
```suggestion
about: Open question such as: I want to use Jina for X, but not sure if it is doable.
```

2022-07-05 15:53 UTC, ArjunSharda commented
Added

2022-07-06 07:22 UTC, JohannesMessner commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Find your solution from our documentations
```suggestion
    about: Find your solution from our documentation
```

2022-07-06 10:55 UTC, ArjunSharda commented
> Hey @ArjunSharda ,
> 
> 
> 
> Thanks for the contribution, can you please check our `https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md` guidelines to check how to have a proper commit message?
Updated.

2022-07-06 10:56 UTC, JoanFM commented
The best way is to open a new PR from a new branch with a correct commit message

2022-07-07 16:03 UTC, ArjunSharda commented
> > The best way is to open a new PR from a new branch with a correct commit message
> 
> You mean like the commit message descriptions?

Bumping this, @JoanFM

2022-07-09 14:20 UTC, closed without merging