feat: add failed and successful request number metrics
jina-ai/jina pull request #5079
Opened 2022-08-22 07:13 UTC by alaeddine-13

**Goals:**
add number of successful and failed request metrics to gateway and worker level
closes https://github.com/jina-ai/jina/issues/5076

2022-08-22 12:37 UTC, samsja commented on jina/serve/runtimes/gateway/request_handling.py
> +            self._failed_requests_metrics = Gauge(
I believe this should be a Counter and not a Gauge since the number cannot decrease

2022-08-22 12:37 UTC, samsja commented on jina/serve/runtimes/gateway/request_handling.py
> +            self._successful_requests_metrics = Gauge(
Same : I believe this should be a Counter and not a Gauge since the number cannot decrease

2022-08-22 12:37 UTC, samsja commented on jina/serve/runtimes/worker/__init__.py
> +            self._failed_requests_metrics = Gauge(
Same: I believe this should be a Counter and not a Gauge since the number cannot decrease

2022-08-22 12:37 UTC, samsja commented on jina/serve/runtimes/worker/__init__.py
> +            self._successful_requests_metrics = Gauge(
Same: I believe this should be a Counter and not a Gauge since the number cannot decrease

2022-08-22 12:37 UTC, samsja commented on jina/serve/runtimes/gateway/request_handling.py
> +    def _update_end_request_metrics(self, result: 'Request', e: Exception = None):
Can we rename e to `excpetion` or something a bit more verbose ? I find it hard to read the code otherwise

2022-08-22 12:37 UTC, samsja reviewed
The PR looks good ! I have so minor comments

2022-08-22 12:42 UTC, samsja requested changes
Requesting change

2022-08-22 13:05 UTC, JohannesMessner commented on jina/serve/runtimes/request_handlers/data_request_handler.py
> +        # somehow exception not raised here and skips directly to counter, should be caught in jina/serve/runtimes/worker/__init__.py instead
I am not sure if this is a useful comment outside of the context of reviewing this PR. A 3rd party will not know what exception and what counter this is talking about.

2022-08-22 16:03 UTC, alaeddine-13 commented on tests/integration/monitoring/test_monitoring.py
> +def test_failed_successful_request_count(port_generator, failing_executor):
> test where the network itself fails that would be nice
should make sense for network failure between executor and gateway, will implement this

> failure case are timeouts between gateway and Executor
will include this, but I believe timeout will only be detected at the gateway level

2022-08-22 16:20 UTC, alaeddine-13 commented on tests/integration/monitoring/test_monitoring.py
> +def test_failed_successful_request_count(port_generator, failing_executor):
case tested in `test_timeout_send`

2022-08-23 08:40 UTC, alaeddine-13 commented on tests/integration/monitoring/test_monitoring.py
> +def test_failed_successful_request_count(port_generator, failing_executor):
network failure case implemented in test_kill_worker

2022-08-23 08:49 UTC, JohannesMessner submitted a review, later dismissed
LGTM, should be a very useful metric to have!

2022-08-23 11:01 UTC, samsja requested changes
I belive we need to rename the metrics so that it follow the [prometheus naming convention](https://prometheus.io/docs/concepts/metric_types/)

We need to remove the "number" from the name it should be implicit with the `total` at the end

I propose to rename like this

`number_of_successful_requests` to `successful_requests`
`number_of_failed_requests` to `failed_requests`

2022-08-23 14:09 UTC, samsja submitted a review, later dismissed
Great PR !

2022-08-23 14:41 UTC, samsja approved these changes

2022-08-23 15:18 UTC, merged