docs(jcloud): adapt to new api
jina-ai/jina pull request #5385
Opened 2022-11-13 06:48 UTC by deepankarm

**Goals:**

- resolves #ISSUE-NUMBER
- ...
- ...

- ...
- ...
- [ ] check and update documentation. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#-contributing-documentation) and ask the team.

2022-12-06 09:15 UTC, alaeddine-13 reviewed
one of core principles is not to only introduce breaking changes after 2 minors since a deprecation is added. I guess here we don't do the same.
Should we ignore this principle for this case ?

2022-12-06 09:37 UTC, zac-li commented on docs/fundamentals/jcloud/yaml-spec.md
> +A Flow deployment without a gateway is often used for {ref}`external-executors`, which can be shared over different Flows. You can expose an Executor by setting `expose: true`:
Good point, just updated, please review!

2022-12-07 15:36 UTC, alexcg1 commented on docs/concepts/jcloud/yaml-spec.md
> +By default, we attach an `efs` to all Executors in a Flow. The benefits of doing so is - it can grow dynamically, so you don't need to shrink/grow volumes as and when necessary.
```suggestion
By default, we attach an `efs` to all Executors in a Flow. This lets the `efs` grow dynamically, so you don't need to shrink/grow volumes as and when necessary.
```

"it" in original text refers to "efs", right? Not Flow? Or Executor?

2022-12-07 15:36 UTC, alexcg1 commented on docs/concepts/jcloud/yaml-spec.md
> +By default, the JCloud gateway will close connections that have been idle for over 600 seconds. If you want longer a connection timeout threshold, you can change the `timeout` parameter under `gatewa
```suggestion
By default, the JCloud gateway will close connections that have been idle for over 600 seconds. If you want a longer connection timeout threshold, change the `timeout` parameter under `gateway.jcloud`.
```

2022-12-07 15:37 UTC, alexcg1 commented on docs/concepts/jcloud/yaml-spec.md
> +If you'd like to customize the gateway's CPU or memory, you can specify the `memory` and/or `cpu` argument under `gateway.jcloud.resources`:
```suggestion
To customize the gateway's CPU or memory, specify the `memory` and/or `cpu` arguments under `gateway.jcloud.resources`:
```

2022-12-07 15:37 UTC, alexcg1 commented on docs/concepts/jcloud/yaml-spec.md
> +A Flow deployment without a gateway is often used for {ref}`external-executors`, which can be shared over different Flows. You can expose an Executor by setting `expose: true` (and un-expose the Gate
```suggestion
A Flow deployment without a gateway is often used for {ref}`external-executors`, which can be shared between different Flows. You can expose an Executor by setting `expose: true` (and un-expose the Gateway by setting `expose: false`):
```

2022-12-07 17:03 UTC, alaeddine-13 approved these changes

2022-12-08 01:02 UTC, zac-li commented on docs/concepts/jcloud/yaml-spec.md
> +If you'd like to customize the gateway's CPU or memory, you can specify the `memory` and/or `cpu` argument under `gateway.jcloud.resources`:
👍🏼 fixed

2022-12-08 01:03 UTC, zac-li commented on docs/concepts/jcloud/yaml-spec.md
> +A Flow deployment without a gateway is often used for {ref}`external-executors`, which can be shared over different Flows. You can expose an Executor by setting `expose: true` (and un-expose the Gate
👍🏼 fixed

2022-12-08 01:10 UTC, zac-li commented on docs/concepts/jcloud/yaml-spec.md
> +By default, the JCloud gateway will close connections that have been idle for over 600 seconds. If you want longer a connection timeout threshold, you can change the `timeout` parameter under `gatewa
fixed

2022-12-08 08:56 UTC, alexcg1 requested changes
Just a couple of small things. Otherwise looking good!

2022-12-08 08:56 UTC, alexcg1 commented on docs/concepts/jcloud/yaml-spec.md
> +A Flow deployment without a gateway is often used for {ref}`external-executors`, which can be shared between different Flows. You can expose an Executor by setting `expose: true` (and un-expose the G
```suggestion
A Flow deployment without a Gateway is often used for {ref}`external-executors`, which can be shared between different Flows. You can expose an Executor by setting `expose: true` (and un-expose the Gateway by setting `expose: false`):
```

2022-12-08 08:56 UTC, alexcg1 commented on docs/concepts/jcloud/yaml-spec.md
> +By default, we attach an `efs` to all Executors in a Flow. This lets the `efs` grow dynamically, so you don't need to shrink/grow volumes as and when necessary.
```suggestion
By default, we attach an `efs` to all Executors in a Flow. This lets the `efs` resize dynamically, so you don't need to shrink/grow volumes manually.
```

2022-12-08 09:46 UTC, zac-li commented on docs/concepts/jcloud/yaml-spec.md
> +By default, we attach an `efs` to all Executors in a Flow. This lets the `efs` grow dynamically, so you don't need to shrink/grow volumes as and when necessary.
fixed!

2022-12-08 09:46 UTC, zac-li commented on docs/concepts/jcloud/yaml-spec.md
> +A Flow deployment without a gateway is often used for {ref}`external-executors`, which can be shared between different Flows. You can expose an Executor by setting `expose: true` (and un-expose the G
fixed!

2022-12-08 10:56 UTC, merged