docs: change executor uri to "jinaai"
jina-ai/jina pull request #5450
Opened 2022-11-25 12:47 UTC by delgermurun

**Goals:**

- Adapt new executor URI on docs
- ...
- ...

- ...
- ...
- [ ] check and update documentation. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#-contributing-documentation) and ask the team.

2022-11-25 15:45 UTC, alaeddine-13 commented on docs/fundamentals/executor/hub/use-hub-executor.md
>  # SECRET must be provided for private Executor
let's also handle a case for private executors. Maybe let's say now we have to login to jina hub ?

2022-11-25 15:45 UTC, alaeddine-13 commented on docs/fundamentals/executor/hub/use-hub-executor.md
>  To use a private Executor, you must provide the `SECRET` which is generated after `jina hub push`.
let's also update this

2022-11-28 09:08 UTC, JoanFM requested changes
In the `Hub` section we should add a section about `Resources` and a clear explanation of this pattern. Also explaining that the old behavior will still be suppoorted for backwards compatibility

2022-11-28 12:22 UTC, JoanFM requested changes
This requires a lot of changes

2022-12-01 16:45 UTC, JoanFM approved these changes

2022-12-01 16:45 UTC, merged