feat: add get_streamer helper and inject streamer info
jina-ai/jina pull request #5472
Opened 2022-12-01 12:56 UTC by alaeddine-13

Add get_streamer helper function

2022-12-01 14:08 UTC, JoanFM requested changes
add this env arg to environment vars in documentation and __init__

2022-12-01 16:28 UTC, JoanFM requested changes
in `jina/__init__.py` u have a list of env vars to add

2022-12-01 16:32 UTC, alaeddine-13 commented
u have a list of env

done

2022-12-05 08:42 UTC, JoanFM approved these changes

2022-12-05 08:43 UTC, merged