fix: support python 3.11
jina-ai/jina pull request #5529
Opened 2022-12-15 15:55 UTC by Jackmin801

**Goals:**

- resolves #5525 
- [ ] fix in x86
- [ ] fix in aarch64
- [ ] check and update documentation. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#-contributing-documentation) and ask the team.

2022-12-15 16:04 UTC, JoanFM requested changes
1.49.0 will make our CI too flaky

2022-12-19 12:21 UTC, JoanFM approved these changes

2022-12-19 12:40 UTC, alaeddine-13 commented on setup.py
> +        final_deps.remove(dep)
```suggestion
    for dep in list(final_deps):
        if dep.startswith('grpcio'):
            final_deps.remove(dep)
```

2022-12-19 15:20 UTC, JoanFM approved these changes

2022-12-19 15:21 UTC, merged