docs: common args inheritence from Flow API
jina-ai/jina pull request #5535
Opened 2022-12-16 15:10 UTC by AnneYang720

**Goals:**

- resolves #5353 
- [ ] check and update documentation. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#-contributing-documentation) and ask the team.

2022-12-16 15:14 UTC, alaeddine-13 commented on docs/concepts/flow/basics.md
> +```{tip}
important instead of tip

2022-12-16 15:14 UTC, alaeddine-13 commented on docs/concepts/flow/basics.md
> +All arguments received by `Flow()` API will be propagated to other entities (gateway, executor) with the following exclusions:
```suggestion
All arguments received by `Flow()` API will be propagated to other entities (gateway, executor) with the following exceptions:
```

2022-12-16 15:15 UTC, alaeddine-13 reviewed
I think the changes should be in create section https://docs.jina.ai/concepts/flow/basics/#create

2022-12-16 15:16 UTC, alaeddine-13 commented
Also update the docstring of flow constructor (we want to see such information in the flow constructor API)
https://docs.jina.ai/api/jina.orchestrate.flow.base/#jina.orchestrate.flow.base.Flow

2022-12-16 16:54 UTC, JoanFM commented on docs/concepts/flow/basics.md
> +- `uses` and `uses_with` won't be passed to gateway
```suggestion
- `uses` and `uses_with` won't be passed to Gateway
```

2022-12-16 16:54 UTC, JoanFM commented on docs/concepts/flow/basics.md
> +- `port`, `port_monitoring`, `uses` and `uses_with` won't be passed to executor
```suggestion
- `port`, `port_monitoring`, `uses` and `uses_with` won't be passed to Executor
```

2022-12-16 16:54 UTC, JoanFM requested changes

2022-12-16 16:54 UTC, JoanFM commented on docs/concepts/flow/basics.md
> +All arguments received by `Flow()` API will be propagated to other entities (gateway, executor) with the following exceptions:
```suggestion
All arguments received by `Flow()` API will be propagated to other entities (Gateway, Executor) with the following exceptions:
```

2022-12-16 16:54 UTC, JoanFM commented on jina/orchestrate/flow/base.py
> +        - `uses` and `uses_with` won't be passed to gateway
same here

2022-12-16 16:54 UTC, JoanFM commented on jina/orchestrate/flow/base.py
> +        - `port`, `port_monitoring`, `uses` and `uses_with` won't be passed to executor
same here

2022-12-19 10:47 UTC, alexcg1 commented
@scott-martens if you have time today could you handle this?

2022-12-19 11:01 UTC, scott-martens commented
Documentation change looks good to me.

2022-12-19 12:29 UTC, alaeddine-13 commented on docs/concepts/flow/basics.md
> +All arguments received by `Flow()` API will be propagated to other entities (Gateway, Executor) with the following exceptions:
```suggestion
All arguments received by {class}`~jina.Flow()` API will be propagated to other entities (Gateway, Executor) with the following exceptions:
```

2022-12-19 12:29 UTC, alaeddine-13 commented on jina/orchestrate/flow/base.py
> +        All arguments received by `Flow()` API will be propagated to other entities (Gateway, Executor) with the following exceptions:
```suggestion
        All arguments received by {class}`~jina.Flow()` API will be propagated to other entities (Gateway, Executor) with the following exceptions:
```

2022-12-19 13:07 UTC, JoanFM approved these changes

2022-12-19 13:07 UTC, merged