feat: add secrets concept to Jina(k8s)
jina-ai/jina pull request #5557
Opened 2022-12-26 14:12 UTC by AnneYang720

**Goals:**

- resolves #5238 
- [ ] add `env_from_secret` to parser
- [ ] support `env_from_secret` in k8s yaml generation
- [ ] add related tests
- [ ] check and update documentation. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#-contributing-documentation) and ask the team.

2022-12-28 13:04 UTC, alaeddine-13 reviewed
I believe we need more docs in https://docs.jina.ai/cloud-nativeness/kubernetes/. We can have a separate section where we explain how to define secrets and create/use them with jina and k8s

2022-12-28 13:04 UTC, alaeddine-13 commented on tests/k8s/test_k8s.py
> +        assert password == '123456'
maybe also one more assert where we send a request to the executor and it returns the value of those variables ? just add an extra endpoint to test-executor

2022-12-28 13:04 UTC, alaeddine-13 commented on docs/cloud-nativeness/k8s.md
> +- Manage credentials of your Executor with secrets, you can use `f.add(..., env_from_secret={'SECRET_PASSWORD': {'name': 'mysecret', 'key': 'password'}})` to map them to Pod environment variables
Let's also say that this (for now) will only work for kubernetes secrets

2022-12-29 08:24 UTC, JoanFM requested changes

2022-12-29 08:24 UTC, JoanFM commented on docs/cloud-nativeness/kubernetes.md
> +After creating the namespace, you need to create the secrets metioned above:
Put a link to `secrets` in `kubernetes` so people know about

2022-12-29 08:24 UTC, JoanFM commented on docs/concepts/flow/executor-args.md
> +| `env_from_secret` | Dictionary of keyword arguments that will override the `env_from_secret` configuration | `object` | `None` |
Are we sure is the good description?

2022-12-29 08:24 UTC, JoanFM commented on jina/orchestrate/deployments/config/helper.py
> +        container_args.extend(['--env-from-secret', json.dumps(env_from_secret)])
I do not think `env_from_secret` should be added to the `container`. This is an `orchestration` argument and should not be seen by the `runtime`

2022-12-29 08:24 UTC, JoanFM commented on jina/orchestrate/deployments/config/k8s.py
> +            env_from_secret = self.deployment_args.env_from_secret
no need of this as well

2022-12-29 08:24 UTC, JoanFM commented on jina/parsers/orchestrate/runtimes/worker.py
> +    Dictionary of keyword arguments that will override the `env_from_secret` configuration
improve description here. Also, the `parser` is not the correct, this should be in the `deployment` mixin

2022-12-29 08:24 UTC, JoanFM commented on tests/k8s/test_k8s.py
> +        secret = client.V1Secret(
put this in a `fixture` I would say makes it more clear and clean

2022-12-29 12:54 UTC, alaeddine-13 commented on docs/cloud-nativeness/kubernetes.md
> +After creating the namespace, you need to create the secrets metioned above:
```suggestion
After creating the namespace, you need to create the secrets mentioned above:
```

2022-12-29 12:54 UTC, alaeddine-13 commented on docs/cloud-nativeness/kubernetes.md
> +```
can we create 2 examples ?
first one is in python (the current example) and the second one is with flow YAML and using command `jina export ...` command. Use a tab to separate between both examples

2022-12-29 15:53 UTC, JoanFM approved these changes

2022-12-29 16:04 UTC, merged