docs: add ephemeral storage
jina-ai/jina pull request #5583
Opened 2023-01-09 09:41 UTC by tarrantro

**Goals:**

- add `ephemeral` storage to documents, [#202](https://github.com/jina-ai/jina-operator/pull/202)

- [ ] check and update documentation. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#-contributing-documentation) and ask the team.

2023-01-09 09:47 UTC, deepankarm requested changes

2023-01-09 09:47 UTC, deepankarm commented on docs/concepts/jcloud/yaml-spec.md
> +`ephemeral` storage will assign space to Executor when it created, and exists as long as that Pod is running on that node. When an Executor is removed or rescheduled for any reason, the data in the `
Terms like `Pod`, `Node` etc might be irrelevant to Jina users. We can say,

It is a temporary storage that grows & shrinks automatically, but data might be lost if Executors are restarted.

2023-01-09 09:47 UTC, deepankarm commented on docs/concepts/jcloud/yaml-spec.md
> +- Default storage size is 5G, maximun storage size parameter is `10G`.
~~maximun~~ maximum

2023-01-10 12:02 UTC, alexcg1 requested changes

2023-01-10 12:02 UTC, alexcg1 commented on docs/concepts/jcloud/yaml-spec.md
> +By default, we assign an `ephemeral` to all Executors in a Flow. This lets the `ephemeral` resize dynamically, so you don't need to shrink/grow volumes manually.
```suggestion
By default, we assign `ephemeral` storage to all Executors in a Flow. This lets the storage resize dynamically, so you don't need to shrink/grow volumes manually.
```

2023-01-11 09:18 UTC, zac-li commented on docs/concepts/jcloud/yaml-spec.md
> +If your Executor needs to share data with other Executors and retain data persistency., consider using `efs`. Note that:
remove the `.` from `.,`?

2023-01-11 09:18 UTC, zac-li commented on docs/concepts/jcloud/yaml-spec.md
> +- Default storage size is 5G, maximum storage size parameter is `10G`.
`5G` instead of 5G

2023-01-11 09:18 UTC, zac-li commented on docs/concepts/jcloud/yaml-spec.md
> +- IO performance be slower compared to `ebs` or `ephemeral`
IO performance is slower (instead of `be`)

2023-01-11 09:27 UTC, alexcg1 reviewed
Thanks for the feedback @zac-li. I must've been really tired when I made my last review :sweat:

2023-01-11 09:27 UTC, alexcg1 commented on docs/concepts/jcloud/yaml-spec.md
> +If your Executor needs to share data with other Executors and retain data persistency., consider using `efs`. Note that:
```suggestion
If your Executor needs to share data with other Executors and retain data persistency, consider using `efs`. Note that:
```

2023-01-11 09:27 UTC, alexcg1 commented on docs/concepts/jcloud/yaml-spec.md
> +- IO performance be slower compared to `ebs` or `ephemeral`
```suggestion
- IO performance is slower compared to `ebs` or `ephemeral`
```

2023-01-11 09:27 UTC, alexcg1 commented on docs/concepts/jcloud/yaml-spec.md
> +- Default storage size is 5G, maximum storage size parameter is `10G`.
```suggestion
- Default storage size is `5G`, maximum storage size parameter is `10G`.
```

2023-01-13 04:10 UTC, deepankarm approved these changes

2023-01-13 07:13 UTC, alexcg1 approved these changes
LGTM :+1:

2023-01-13 08:02 UTC, merged