docs: caution users about exceptions inside Flow context
jina-ai/jina pull request #5615
Opened 2023-01-20 14:11 UTC by girishc13

**Goals:**

- clarifies issue in #5596 
- [x] check and update documentation. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#-contributing-documentation) and ask the team.

2023-01-23 12:23 UTC, alaeddine-13 submitted a review, later dismissed

2023-01-23 14:24 UTC, alexcg1 requested changes

2023-01-23 14:24 UTC, alexcg1 commented on docs/concepts/flow/index.md
> +surround the statements that can potentially raise an exception with a `try-except` block.
```suggestion
The statement `with f:` starts the Flow, and exiting the indented with block stops the Flow, including all Executors defined in it.
Exceptions raised inside the `with f:` block will close the Flow context manager. If you don't want this, use a `try...except` block to surround the statements that could potentially raise an exception.
```

2023-01-23 15:01 UTC, alexcg1 approved these changes
LGTM :+1:

2023-01-23 16:01 UTC, girishc13 commented
@JoanFM Can you merge this?

2023-01-24 11:41 UTC, JoanFM approved these changes

2023-01-24 11:41 UTC, merged