fix: docstrings-english
jina-ai/jina pull request #5718
Opened 2023-02-27 09:55 UTC by alexcg1

- Fix English
- Update outdated docarray docs URLs (docarray.jina.ai to docs.docarray.org)
- Jina Hub -> Executor Hub
- Standardize punctuation, tenses

There are still some links to https://docs.jina.ai/concepts/flow/create-flow/#complex-flow-topologies which need to be fixed. What can I change that to (URL 404s right now)

- [X] check and update documentation. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#-contributing-documentation) and ask the team.

2023-02-27 10:24 UTC, JoanFM requested changes

2023-02-27 10:24 UTC, JoanFM commented on jina/orchestrate/deployments/__init__.py
>          return self.args.uses.startswith('docker://') or self.args.uses.startswith(
let me do a change on top

2023-03-01 08:47 UTC, JoanFM approved these changes

2023-03-28 09:59 UTC, alexcg1 commented
Any actions need to be taken on this @JoanFM ?

2023-04-20 08:38 UTC, merged