feat: easier setup
jina-ai/jina pull request #5750
Opened 2023-03-09 08:15 UTC by alaeddine-13

getting rid of the need to create folders and pass bootstrap parameter

2023-03-09 08:40 UTC, JoanFM requested changes

2023-03-09 08:40 UTC, JoanFM commented on jina/orchestrate/deployments/__init__.py
> +            if self._pods[0].args.stateful:
does it affect if I add an already-existing voter?

2023-03-09 08:40 UTC, JoanFM commented on jina/serve/consensus/run.go
> +func get_configuration(self *C.PyObject, args *C.PyObject) *C.PyObject {
does not passed the `header` file declaration

2023-03-21 15:28 UTC, JoanFM approved these changes

2023-03-21 15:38 UTC, alaeddine-13 commented on jina/serve/consensus/run.go
> +        defer C.free(unsafe.Pointer(cstr))
will attempt to remove it and update

2023-03-21 15:40 UTC, merged

2023-03-21 15:40 UTC, JoanFM commented on jina/serve/consensus/run.go
> +        defer C.free(unsafe.Pointer(cstr))
let's do in separate PR, let's go for next milestone here