docs(jcloud): add storage section
jina-ai/jina pull request #5831
Opened 2023-04-25 14:27 UTC by npitsillos

**Goals:**

- Fixes naming for components in `jcloud`
- Adds missing `storage` section
- Fixes description of `target` in autoscaling

- [x] check and update documentation. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#-contributing-documentation) and ask the team.

2023-04-25 15:39 UTC, alexcg1 requested changes

2023-04-26 08:17 UTC, npitsillos commented on docs/concepts/jcloud/configuration.md
> +| target | 100         | int                      | Target value of `metric` after which replicas autoscale |
Could you be more specific here @alexcg1 which parts should be wrapped?

2023-04-27 08:52 UTC, alexcg1 requested changes

2023-04-27 08:52 UTC, alexcg1 commented on docs/concepts/jcloud/configuration.md
> +JCloud also supports retaining the data a Flow was using while active. You can set the `retain` argument to `true` to enable this feature.
```suggestion
JCloud also supports retaining the data that a Flow was using while it was active. You can set the `retain` argument to `true` to enable this feature.
```

2023-04-28 10:02 UTC, merged