docs(readme): llm-generative-art revamp
jina-ai/jina pull request #5895
Opened 2023-05-25 11:59 UTC by alexcg1

Revamp of readme to focus more on LLMs and generative stuff

2023-05-30 09:00 UTC, JoanFM requested changes

2023-05-30 11:45 UTC, alexcg1 commented on README-bullet-short.md
> +- Build applications for any [data type](), any mainstream [deep learning framework](), and any [gateway]().
I'll change to "popular gateways" or "commonly-used gateways"

2023-05-30 13:09 UTC, JoanFM commented on README-bullet-short.md
> +- Build applications for any [data type](), any mainstream [deep learning framework](), and any [gateway]().
But what do u mean here?

2023-05-30 13:47 UTC, JoanFM commented on README-bullet-short.md
> +- Build applications for any [data type](), any mainstream [deep learning framework](), and any [gateway]().
okey, protocols

2023-05-31 13:10 UTC, alexcg1 commented on README-bullet-short.md
> +- Build applications for any [data type](), any mainstream [deep learning framework](), and any [gateway]().
Fixed. In README.md, not this short-bullet form

2023-06-14 09:35 UTC, alexcg1 commented
Note, I'm completely removing the notebook because:

- StableLM Executor in Deployment won't work in Colab due to GPU/memory constraints
- TextToImage Executor in Flow won't work because Hub Executors won't be sharable/reusable soon
- As @samsja said, Jina is seldom used in notebooks anyway
- With DocArray v2 as default, we'd have to refactor anyway

2023-06-14 09:43 UTC, alexcg1 commented
For https://github.com/jina-ai/jina/pull/5895/commits/64fc9cc46f03e47a78f881237bff8fed7d4278a7, I grepped the repo to ensure the images didn't appear anywhere.

I assume they're not called from any external places, right?

2023-06-14 10:22 UTC, alexcg1 commented
@alaeddine-13 @JoanFM can you review? I think I've made all the big changes now

2023-06-14 18:54 UTC, JoanFM requested changes

2023-06-14 18:54 UTC, JoanFM commented on README.md
> +- Free CPU/GPU hosting via [Jina AI Cloud](https://cloud.jina.ai).
This is not Free

2023-06-15 07:12 UTC, alexcg1 commented on README.md
> +- Free CPU/GPU hosting via [Jina AI Cloud](https://cloud.jina.ai).
Fixed

2023-06-15 07:20 UTC, JoanFM approved these changes

2023-06-15 07:32 UTC, merged