feat: add return_type parameter to gateway streamer methods to allow …
jina-ai/jina pull request #6027
Opened 2023-08-11 09:15 UTC by alaeddine-13

closes: https://github.com/jina-ai/jina/issues/6012

GatewayStreamer by default will fetch executor input and output schemas and reconstruct docarray models dynamically. The output schemas will be used to cast the responses at the gateway level.
Although the casted responses are nearly identical to the original schemas defined at executor level, they might fail some checks, for instance, if the user defines a doc schema `MyDoc`, the following check will fail:
`assert isinstance(doc, MyDoc)`
similarly, adding `doc` to a DocList[MyDoc] will fail the type checking.

This PR allows the user of a GatewayStreamer to specify the return_type that will be used for casting and the output responses received from methods of the gateway streamer will match exactly the specified `return_type`.

2023-08-15 11:26 UTC, alaeddine-13 commented
Currently this PR depends on an issue with @docarray:
@docarray's UpdateMixin, only updates a document if the other document is exactly the same type.
However, there are cases where 2 documents are generated from dynamic schemas that are exactly the same. Even though the fields are exactly the same, the update operation will fail because in docarray checks that the schemas belong to the same reference

2023-08-22 12:37 UTC, alaeddine-13 commented
depends on https://github.com/docarray/docarray/pull/1755

2023-08-24 08:06 UTC, JoanFM requested changes

2023-08-24 08:06 UTC, JoanFM commented on .github/workflows/ci.yml
> +          pip uninstall docarray -y
is this still needed? this should not be needed right?

2023-09-14 12:30 UTC, merged