feat(743): add type annotations in jina
jina-ai/jina pull request #947
Opened 2020-09-15 02:16 UTC by rameshwara

Solution to issue #743

2020-09-15 20:22 UTC, maximilianwerk commented
Hey @rameshwara,
Thanks a lot for your contribution. It is really helpful.
In order to let our CI pipeline be runnable again, could you switch back the jina-hub branch to `e07232`. Since we use the jina-hub as a submodule inside jina itself, the CI pipeline must be able to pick up the hub branch (which most probably was only updated locally on yourmachine).
Cheers

2020-09-16 14:15 UTC, rameshwara commented
Hi @maximilianwerk, thanks for the response. Apparently I am working on the jina branch and not the jina-hub branch. So I don't understand why CI pipeline was not runnable. And I am not able to find the branch e07232. Can you please provide more details about the branch to which I need to switch to?

2020-09-17 08:21 UTC, JoanFM requested changes

2020-09-17 08:21 UTC, JoanFM commented on jina/docker/database.py
> +    def insert(self, document: str) -> str:
why is this added here? maybe some merge issue?

2020-09-17 08:21 UTC, JoanFM commented on jina/docker/hubio.py
> +    def _write_summary_to_file(self, summary: Dict) -> None:
same here, seems like some merge issue

2020-09-17 08:21 UTC, JoanFM commented on jina/drivers/__init__.py
> +    def _traverse_apply(self, docs: List, *args, **kwargs) -> None:
docs are `Iterable['jina_pb2.Document']`

2020-09-17 08:21 UTC, JoanFM commented on jina/executors/clients.py
> +    def get_output(self, response: grpc.UnaryUnaryMultiCallable) -> None:
not really convinced if this is true for child classes, and I think in these cases, interface type is cleaner if provided by the parent

2020-09-17 08:21 UTC, JoanFM commented on jina/executors/decorators.py
> +def _get_size(data: Union[Iterator[Any], List[Any], np.ndarray], axis: int = 0) -> Union[Tuple, int, None]:
better to say `Optional[Tuple, int]`

2020-09-17 08:21 UTC, JoanFM commented on jina/executors/indexers/keyvalue.py
> +    def get_query_handler(self) -> None:
since children behave differently I would not put this one

2020-09-17 08:21 UTC, JoanFM commented on jina/helper.py
> +def expand_env_var(v: str) -> Union[str, Any]:
Union[str, Any] seems equivalent to `Any`?

2020-09-17 08:21 UTC, JoanFM commented on jina/peapods/__init__.py
> +def Pea(args: 'argparse.Namespace' = None, allow_remote: bool = True, **kwargs) -> Union['RemotePea', 'ContainerPea', 'HeadPea', 'TailPea', 'BasePea']:
`BasePea` is the parent class, so by claiming u return `BasePea` you are having a correct statement

2020-09-17 08:21 UTC, JoanFM commented on jina/peapods/__init__.py
> +def Pod(args: Union['argparse.Namespace', Dict] = None, allow_remote: bool = True, **kwargs) -> Union['MutablePod', 'RemoteMutablePod', 'RemotePod', 'BasePod']:
equivalent here

2020-09-17 08:21 UTC, JoanFM commented on jina/peapods/pea.py
> +def _get_event(obj: 'BasePea') -> Union[Event, None]:
`Optional[Event]`

2020-09-17 08:38 UTC, maximilianwerk commented
> Hi @maximilianwerk, thanks for the response. Apparently I am working on the jina branch and not the jina-hub branch. So I don't understand why CI pipeline was not runnable. And I am not able to find the branch e07232. Can you please provide more details about the branch to which I need to switch to?

We use git submodules in order to include the jina-hub code into the jina repository. It might have happened, that you (by accident or since you worked on an older master branch) changed to an older version of this git submodule. In order to get back to the latest one, you can run `git submodule update --init` which should set it back to the currently used one. Please give it a try. Furthermore, here is an example to showcase how changing the head of the submodule would look like in the jina repository:

![image](https://user-images.githubusercontent.com/4920275/93446611-af3bb300-f8d1-11ea-9bf4-4d26cf5cf7fd.png)

2020-09-17 10:09 UTC, rameshwara commented
> > Hi @maximilianwerk, thanks for the response. Apparently I am working on the jina branch and not the jina-hub branch. So I don't understand why CI pipeline was not runnable. And I am not able to find the branch e07232. Can you please provide more details about the branch to which I need to switch to?
> 
> We use git submodules in order to include the jina-hub code into the jina repository. It might have happened, that you (by accident or since you worked on an older master branch) changed to an older version of this git submodule. In order to get back to the latest one, you can run `git submodule update --init` which should set it back to the currently used one. Please give it a try. Furthermore, here is an example to showcase how changing the head of the submodule would look like in the jina repository:
> 
> ![image](https://user-images.githubusercontent.com/4920275/93446611-af3bb300-f8d1-11ea-9bf4-4d26cf5cf7fd.png)

@maximilianwerk I did try running 'git submodule update --init' now. But there are no changes observed upon running the command.

2020-09-17 11:14 UTC, maximilianwerk commented
Could you paste me the results from the `git status` command?

2020-09-17 13:56 UTC, rameshwara commented
> Could you paste me the results from the `git status` command?

![image](https://user-images.githubusercontent.com/13378629/93480987-b12a6400-f91b-11ea-96fd-fb25eb0bbc6b.png)

2020-09-17 13:58 UTC, closed without merging

2020-09-18 05:55 UTC, maximilianwerk commented
> > Could you paste me the results from the `git status` command?
> 
> ![image](https://user-images.githubusercontent.com/13378629/93480987-b12a6400-f91b-11ea-96fd-fb25eb0bbc6b.png)

I am still not sure, what went wrong, but I see that everything seems to work in the other PR. Great!