feat: add type annotations to jina drivers
jina-ai/jina pull request #962
Opened 2020-09-17 18:50 UTC by rameshwara

feat: add type annotations to jina drivers queryset

2020-09-17 20:04 UTC, JoanFM requested changes

2020-09-17 20:04 UTC, JoanFM commented on jina/drivers/__init__.py
> +    def _traverse_apply(self, docs, *args, **kwargs) -> None:
docs is an Iterable[jina_pb2.Document]

2020-09-17 20:04 UTC, JoanFM commented on jina/drivers/__init__.py
> +    def _dump_instance_to_yaml(data) -> Dict:
Is there any hint on the type of data? And the actual type of Dict?

2020-09-17 20:15 UTC, rameshwara commented
Is there a reason why this is happening?

![image](https://user-images.githubusercontent.com/13378629/93523353-90c8cc80-f950-11ea-877c-b649851b6714.png)

2020-09-17 21:01 UTC, JoanFM reviewed
Please keep a PR per package at least.

2020-09-17 21:51 UTC, rameshwara commented
> Please keep a PR per package at least.

Done, have removed the additions in executors.

2020-09-18 05:36 UTC, JoanFM approved these changes

2020-09-18 05:37 UTC, merged