docs: update tutorial collection
jina-ai/jina pull request #978
Opened 2020-09-22 12:01 UTC by maximilianwerk

Updated the tutorial section to be in sync with the currently running examples. Hope I got the buzzwords right.

2020-09-22 12:03 UTC, JoanFM requested changes

2020-09-22 12:03 UTC, JoanFM commented on README.md
> +Search cross model to get images from captions and vice versa
typo in model (it is cross modal)

2020-09-22 13:09 UTC, alexcg1 commented
Somehow the table got dropped at the end of the README :(

2020-09-23 06:30 UTC, maximilianwerk commented
> Somehow the table got dropped at the end of the README :(

That was a missing table tag.

2020-09-23 07:27 UTC, hanxiao commented on README.md
>  ## Documentation
```suggestion

## Documentation
```

2020-09-23 07:28 UTC, hanxiao approved these changes

2020-09-23 07:30 UTC, merged