test: proposal for the new flow traversal
jina-ai/jina pull request #979
Opened 2020-09-22 12:40 UTC by maximilianwerk

This is a new adaption of the traversal tests to do a test-driven development of the new traversal proposal. Furthermore, this allows us to decide whether this is the functionality, we want to achieve.

I choose `traversal_paths=['cmc', 'mcm']` over `traversal_paths=[['c', 'm', 'c'], ['m', 'c', 'm']`, since it easier to read, and especially in the `.yml` files it is much easier to write a list of strings instead of a list of lists of strings.

Furthermore, I added the root identifier `r` to also be able to apply a function to the roots of the trees.

2020-09-22 13:25 UTC, JoanFM commented
I love this test @maximilianwerk , really clarifying to what we have been discussing

2020-09-22 13:54 UTC, hanxiao commented
i will come back to this after all tests are fixed

2020-09-22 13:56 UTC, JoanFM requested changes

2020-09-22 13:56 UTC, JoanFM commented on tests/unit/drivers/test_recursive_traversal_tree.py
> +@pytest.mark.skip('this is a test for the proposed new flow design')
pytest.mark.skip requries `reason` as kwargs, so u need to put `reason='this is ...`

2020-09-23 07:34 UTC, hanxiao commented
did I miss something here? where is `traversal_paths` come from? Can't see this args from our codebase or in this PR?

2020-09-23 07:41 UTC, hanxiao approved these changes

2020-09-23 07:42 UTC, hanxiao approved these changes

2020-09-23 07:43 UTC, merged